### PR TITLE
OAUTH2-131 Make abstract and use correct name

### PR DESCRIPTION
**Pull request by csierra**
hey @topolik, 

this pull should have the corrections Brian asked for here: https://github.com/brianchandotcom/liferay-portal/pull/59213#issuecomment-392961574

thx!

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:reopen

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/csierra/liferay-portal/pull/397

View just my changes: https://github.com/topolik/liferay-portal/compare/csierra:bc493f5914...36e90738de
View total diff: https://github.com/topolik/liferay-portal/compare/82d5f0c7f8...36e90738de

**Pull request closed without merging**
