### PR TITLE
[TS] LPS-91254

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-91254

This issue can only be reproduced if we have a legacy algorithm set to something, and the LDAP algorithm set to NONE.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi Chris, 
this should be fixed in LDAP, not password encryptor. We need to know the password encryption algorithm in db.  I solved it by using the prefix but using this we are going back into situation before `passwords.encryption.algorithm.legacy` where we didn't know what algorithm was used previously.

We already check for `algorithm == null`, I don't know why we don't check also for NONE, it has same meaning: https://github.com/topolik/liferay-portal/blob/6ec1c41ff35cf232978c3bf2ca3eaa70d4ee8b65/modules/apps/portal-security/portal-security-ldap-impl/src/main/java/com/liferay/portal/security/ldap/internal/exportimport/DefaultPortalToLDAPConverter.java#L434

Please resend. Thanks.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/topolik/liferay-portal/pull/714

Thanks!

**Pull request closed without merging**
