### PR TITLE
LPS-88596 Don't really have a dependency on batik-css

### PR DESCRIPTION
**Pull request by samuelkong**
cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi @yxingwu,

why do you think Antisamy doesn't use Batik ... https://github.com/nahsra/antisamy/blob/1.5.7/src/main/java/org/owasp/validator/css/CssScanner.java#L38

Did I miss anything?

**Comment by topolik** [comment]
```
java.lang.NoClassDefFoundError: org/apache/batik/css/parser/ParseException                                                                                                                                            at org.owasp.validator.html.AntiSamy.scan(AntiSamy.java:93)                                                                                                                                           
        at com.liferay.portal.security.antisamy.internal.AntiSamySanitizerImpl.sanitize(AntiSamySanitizerImpl.java:109)  

Caused by: java.lang.ClassNotFoundException: org.apache.batik.css.parser.ParseException cannot be found by com.liferay.portal.security.antisamy_4.0.0
```
It is required, please resend. 

Thanks.

**Comment by topolik** [comment]
View total diff: https://github.com/topolik/liferay-portal/compare/65713f08b7...0fcf32f0db

**Pull request closed without merging**
