### PR TITLE
LPS-107889

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/csierra/liferay-portal/pull/644
View total diff: https://github.com/topolik/liferay-portal/compare/34f64688df...2a02c3c1af

**Comment by topolik** [comment]
Thank you, forwarded to @csierra, looks fine from a security perspective.

**Pull request closed without merging**
