### PR TITLE
LPS-60558

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @topolik 

Check Sam's comment here: https://github.com/samuelkong/liferay-portal/pull/720

Sam sent this fix back to me: https://github.com/hhuijser/liferay-portal/pull/2543,
but David clarifies why he thinks this solution is not correct.

Sam's on leave now, so I'll let you figure it out :)

**Comment by samuelkong** [comment]
Added comment on https://github.com/hhuijser/liferay-portal/pull/2543#issuecomment-159976340

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/juliocamarero/liferay-portal/pull/3827

View just my changes: https://github.com/topolik/liferay-portal/compare/hhuijser:2c802b06f2...801dc57bfe
View total diff: https://github.com/topolik/liferay-portal/compare/ac83fb8e7a...801dc57bfe

**Comment by topolik** [comment]
Hi @hhuijser, Julio is on vacation (returning on 30th), but I believe he is the right one to fix this issue. Please let me know if you want me to send it to somebody else, I hope it can wait.

**Pull request closed without merging**
