### PR TITLE
LPS-113348 Only apply cors if OAuth2 is used

### PR DESCRIPTION
**Pull request by csierra**
Hey Tomas, 
I think we discussed this already and said we wanted to document it. I was going to do it but I realized it was easy enough to directly implement it. Do you think this is what we discussed?

In order for this to work properly CORS will only be configurable on the URL's that have OAuth2 enabled already in the portal. Alas that configuration does not have a GUI. I don't know if it should in any case since the portal endpoints that should be eligible to be authorized by OAuth2 are fixed, I would say, since for extensibility we have the `/o/` path. 

Let me know what you think or forward it if you think everything is fine. 

Carlos.

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Please resend as discussed. Thank you.

**Pull request closed without merging**
