### PR TITLE
LPS-60598

### PR DESCRIPTION
**Pull request by neilking**

### CODE REVIEW

**Comment by topolik** [comment]
Hi Neil, 

I'm sorry this is not correct, we already escape the message **before** passing to `<liferay-ui:icon>` please see https://github.com/liferay/liferay-portal/blob/a071db5c8cc10bf32a73c53321522f1c28ad3e7d/modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/view_file_entry.jsp#L474. The message here would be double escaped.

The original commit from @daviddotzhang was almost correct: https://github.com/liferay/liferay-portal/commit/75643b60273f24cb20eed766685888e7a865f071 The correct place to escape is https://github.com/liferay/liferay-portal/blob/90a39f6c6f924965c0f0ad88c27e7c1b93790119/portal-web/docroot/html/taglib/ui/input_asset_links/page.jsp#L91

However, the original commit also escaped `portal-web/docroot/html/taglib/aui/nav_item/end.jsp`, I'm not sure why is that needed. @daviddotzhang?

Please resend. Thank you.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/samuelkong/liferay-portal/pull/758

View just my changes: https://github.com/topolik/liferay-portal/compare/neilking:c4f9f732e5...4982d92c38
View total diff: https://github.com/topolik/liferay-portal/compare/18c62c83ea...4982d92c38

**Comment by topolik** [comment]
Sent for further review to Sam, I see this has long history which I'm not aware of. Thanks.

**Comment by neilking** [comment]
I think the escape code in page.jsp of input_asset_link is not in the master. And that should not be a correct place to escape, because this is not final place the value is used. It should be escaped in liferay-ui:icon, and if there is over-escape, we should remove the escape in other place.

**Comment by topolik** [comment]
Yeah, it was reverted because of the other change in `aui/nav_item/end.jsp`

If you want to fix it in the `<liferay-ui:icon>` then it's fine, I just need a consistent PR to avoid the double escaping.

**Pull request closed without merging**
