### PR TITLE
LPS-75421

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-75421

Sending to you as per your request.  Let me know if you have any questions.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Hi @topolik,

Test errors look unrelated.  Would you mind taking a look at this PR?

Thanks!

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/52913

View just my changes: https://github.com/topolik/liferay-portal/compare/ChrisKian:8196ac3276...7a8c64eb2d
View total diff: https://github.com/topolik/liferay-portal/compare/a59d3007b8...7a8c64eb2d

**Pull request closed without merging**
