### PR TITLE
LPS-90050

### PR DESCRIPTION
**Pull request by samuelkong**
cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi guys,

this won't work for existing deployments. We save the value into DB with every "instance settings" portlet submit.

I believe we want to fix the existing environments with this ticket, correct? For new deployments we already have https://issues.liferay.com/browse/LPS-90049.

I think we need an upgrade process here that looks what's in the database, compares with portal-ext.properties value and the new default value. We need to figure out if user changed the value intentionally and update database accordingly.

If you have more questions please ask.

Please resend, thank you.

**Comment by samuelkong** [comment]
@topolik
I don't think it's worth the effort to add an upgrade process for existing environment. I think it's enough to just fix the default for new deployments. We can add a note to the "Important Changes" section of the release notes for existing environments.

**Comment by martamedio** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/70917

**Pull request closed without merging**
