### PR TITLE
LPS-95013 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by inacionery**
Hi @topolik,

I'm not sure if that's the correct fix for this issue, could you please review it?

Thanks a lot!

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi @inacionery , looks like it cannot compile. Have you updated the dependency reference?

**Comment by topolik** [comment]
So looks like we don't reference this patched dependency anywhere. From where is it used?

**Comment by inacionery** [comment]
Hey @topolik, what compile error are you experiencing? I not found any reference to it, but when it is merged, I will update the reports to use it.

**Comment by topolik** [comment]
Ok, I see. The compile failures were at SF above. But maybe it's unrelated.

> I not found any reference to it, but when it is merged, I will update the reports to use it.

OK, sounds good then.

**Comment by inacionery** [comment]
Great, I'll forward it to BChan. Thx!

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/73483

**Pull request closed without merging**
