### PR TITLE
LPS-86515 TOTP and LPS-86516 HOTP (no configuration pages)

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Already merged. Thanks.

**Pull request closed without merging**
