### PR TITLE
[TECHNICAL-SUPPORT] LPS-87038

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @topolik,
Looks like there is a merge conflict, please let me know if you would like me to resolve it an resend the PR, or if you plan on doing so yourself.  Thanks!

**Comment by topolik** [comment]
Hi guys, this looks wrong. Please avoid changing MainServlet the logic there is already very fragile. Also, OpenID Connect is an SSO so it should be authenticated through it's AutoLogin

**Comment by topolik** [comment]
Also the ticket says something different, what's the root cause here?

**Comment by ChrisKian** [comment]
Hey @topolik,

This issue is caused because we hit the OpenConnectIdFilter first, then onto the MainServlet where we try to login the user.  The problem with this is the OpenConnectIdFilter doesn't set the remoteUserId in the request, so when we hit the MainServlet to login, we don't see we're dealing with a remote user, so we cannot go through the loginUser() method called on line 516.  If we were to go through this method (and not instantly be returned due to null values), we would eventually hit the DefaultLandingPageAction class, which sets the default landing page to what we want.  After that, MainServlet would process redirects and see we have something set for the default landing, and the issue would be solved.

However, because we return early in MainServlet.loginUser, specifically at line 1019, we instead process the redirect using the wrong landing page, and authenticate later. 

Although the AutoLoginFilter is hit and seems to be working properly, it is done so AFTER the OpenConnectIdFilter, which seems to be cause the issue.  If the AutoLoginFilter was called first, we would set the remoteUser value in the request, not return null in MainServlet.getRemoteUser(), and then be able to call the DefaultLandingPageAction BEFORE we actually process the redirect later on in MainServlet.  I chose not to go this route because I wasn't sure how to achieve it, and it seemed to make a much bigger impact than adding a request attribute would.

Please let me know how to proceed.  Thank you for your help!

**Comment by topolik** [comment]
Hi @ChrisKian,

`OpenIdConnectFilter` is executed before `AutoLoginFilter` in order to validate the authorized response from OIDC, prepare session data for `OpenIdConnectAutoLogin` so that `AutoLoginFilter` can authenticate the user - it does create `ProtectedServletRequest` with the correct remote user.

I guess your testing environment is broken because all this is running fine and as expected, user is authenticated, even `DefaultLandingPageAction` is fired and set `LastPath` with the default landing page correctly.

The root cause is probably that OIDC doesn't call `/login/login_redirect` in the end and hence `LastPath` is not used.

Can you please look at it?

Thanks.

**Comment by topolik** [comment]
Please can you also ping @stian-sigvartsen? He can help here, he recently worked with this code and he can provide a lot of guidance. Thanks!

**Comment by stian-sigvartsen** [comment]
Hey @jonathanmccann @ChrisKian . Just wondering if you know if this is a regression? The ticket type is "bug" but we did tweak the LastPath handling a month ago as part of https://issues.liferay.com/browse/LPS-86424

**Comment by ChrisKian** [comment]
Hey @stian-sigvartsen,

So is the assumption LPS-86424 is the correct logic?  I mean to say, the "issue" described in LPS-87038 isn't actually a bug?  Please let me know if this is the case, and keep in mind the user is setting the default landing page, unlike LPS-86424.

Thanks for all your help so far!

**Comment by ChrisKian** [comment]
Hey @stian-sigvartsen, thanks for clearing that up.  Yes, this issue is only when the Default Landing Page is set in the Instance Settings.  If it is not set, the normal Default Landing Page is used, and there is no issue.

@topolik, I believe this is what you were getting at in regards to the "normal, default" Default Landing Page being used with OpenIdConnect.  Although this is true, even if we have set the Default Landing Page within instance settings, the ordering of filters causes the "normal" Default Landing Page to be used, rather than the newly set one.

Basically, when authenticating through OpenIdConnect, we also hit MainServlet.service.  In this method, we attempt to [get the remote user](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/internal/servlet/MainServlet.java#L558).  However, if we do not have a value for the remoteUserId, [we return early in the _loginUser method](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/internal/servlet/MainServlet.java#L1017), basically assuming the user is a guest or otherwise unauthenticated.  By returning early, we completely bypass the pre-login, and more importantly for this issue, [post-login events](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/internal/servlet/MainServlet.java#L1053).  The post-login events are very important, because you can see the [DefaultLandingPageAction event is included](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L4352), and this is the action which redirects to the customized Default Landing Page, if set.

As to your solution:
> The root cause is probably that OIDC doesn't call /login/login_redirect in the end and hence LastPath is not used.

I have tried adding redirects in the OpenIdConnectFilter.processFilter method, but have not had any luck.  If this is the correct approach, could you please offer a bit more guidance as to how we achieve this?

Please let me know if I can provide any more information, or clear up my explanation.  Thanks for your help guys!

**Comment by stian-sigvartsen** [comment]
Hey @ChrisKian. I've prepared some changes to the OIC modules that results in the correct behavior as you describe it. If all goes to plan I will send a pull to @topolik tomorrow and will CC you

**Comment by stian-sigvartsen** [comment]
Hey Tibor. Apologies, I forgot to mention you guys on the pull to Tomas. Here is is: https://github.com/csierra/liferay-portal/pull/468

/cc @lipusz  @jonathanmccann @topolik

**Comment by stian-sigvartsen** [comment]
Hey Tibor. Apologies I forgot to mention you on the pull to Tomas. Please see https://github.com/topolik/liferay-portal/pull/658

/cc @lipusz @topolik @jonathanmccann

**Comment by lipusz** [comment]
@stian-sigvartsen 

Is https://issues.liferay.com/browse/LPS-86424 a dependency for https://issues.liferay.com/browse/LPS-87038?

**Comment by stian-sigvartsen** [comment]
More like a duplicate. When I logged LPS-86424 I wasn't aware of the DefaultLandingPage feature so its original fix wasn't comprehensive enough. Then later LPS-87038 was logged.

So I thin once the pull is closed we can close both tickets and mark LPS-87038 as a duplicate.

**Comment by stian-sigvartsen** [comment]
Or "fixed by" maybe.

**Comment by lipusz** [comment]
I see. Can you please add then the "[TS]" designation to the subject of the PR you sent?

Thanks!

**Comment by stian-sigvartsen** [comment]
Done, thanks for highlighting this 👍

**Pull request closed without merging**
