### PR TITLE
[TECHNICAL-SUPPORT] LPS-56446 Email message sent from Invitation portlet exposes the sender host's user name in the Message-ID header

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-56446

Hi Tom,

This is the follow up of #172 
Checkout the description of the LPS to see how to overcome the regression (https://issues.liferay.com/browse/LPS-51143) on master in the invitation portlet to be able to test and the comments for details.

Thanks,
Tibi

@IstvanD

### CODE REVIEW

**Comment by lipusz** [comment]
Same tests failed on https://github.com/lipusz/liferay-portal/pull/81. Seems unrelated.

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28007. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
