### PR TITLE
[TS] LPS-112260 There shouldn't be UI difference between success and non existing user.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hello @marianoalvarosaiz 

Can you please add the [TS] designation to the subject?

Thank you!

**Comment by topolik** [comment]
Hi @marianoalvarosaiz, 

sorry it took so long. There are still differences, did I miss anything? Thanks.

Screenshot_2020-04-29_18-24-47
Screenshot_2020-04-29_18-24-16

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,

 the aim of this PR was to be back in the same point we were after LPS-94800 was fixed. After LPS-94800 we had the same problem that with my PR: what happens when query reminder is enabled (LPS-71001). To resume, the PR will only "work" in the same situation as LPS-94800, the one that Joshua described in his comment: https://issues.liferay.com/browse/LPS-94800?focusedCommentId=1819186&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1819186

Our failure IMHO is that be ask for the query reminder before we sent the email, not afterwards. That has the inconvenience that there's always going to be a difference in the message since we cannot invent the reminder question for a non existing user. The problem with asking it later is that a user email can easily we filled with plenty of mails if only mail address and captcha is needed. So I guess that we have to decide which alternative we should take.

Kind regards.

**Comment by topolik** [comment]
Hi @marianoalvarosaiz,

please see https://github.com/csierra/liferay-portal/pull/696

Thanks.

**Pull request closed without merging**
