### PR TITLE
LPS-62096 don't sanitize journal article with antisamy to avoid audio/video elements removal

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @topolik can we include this in the official documentation so people are aware of this change? Then, if the Portal Admin or System Admin wants to be less strict they can go to the Portal Configuration and add the models to the whitelist.
Thanks!

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/34558
View total diff: https://github.com/topolik/liferay-portal/compare/993c81ef1b...87f180e347

**Pull request closed without merging**
