### PR TITLE
[TECHNICAL-SUPPORT] LPS-70340

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/46795

View just my changes: https://github.com/topolik/liferay-portal/compare/jonathanmccann:046fb9204d...3b5a2d0092
View total diff: https://github.com/topolik/liferay-portal/compare/a12573ded1...3b5a2d0092

**Pull request closed without merging**
