### PR TITLE
LPS-72931 use Objects.equals to compare Long objects.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by csierra** [comment]
it looks like the failures are real?

**Comment by csierra** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
ci:stop

**Comment by marianoalvarosaiz** [comment]
Hi @csierra, I've sent another one fixing semantic versioning and all test are passed. See https://github.com/topolik/liferay-portal/pull/448

**Comment by csierra** [comment]
ah... ok 👏 👏

**Pull request closed without merging**
