### PR TITLE
LPS-57826

### PR DESCRIPTION
**Pull request by samuelkong**
/cc @bejondshao

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:retest

**Comment by topolik** [comment]
Hi @rotty3000, @jorgeferrer, Q: what's the logic for when to choose staging/live group for permission checking?

Currently we swap the groups only in hasPermissionImpl() ...
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/security/permission/AdvancedPermissionChecker.java#L576-L583

But other PermissionChecker methods do not follow the logic ... hasUserPermission, isGroupAdmin, isGroupOwner, isGroupMember, isContentReviewer, getUserBag

Portal internals depend on it (example - InlineSQLHelperImpl ... https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/security/permission/InlineSQLHelperImpl.java#L71-L72)

So I guess there might be more issues like this one.

BUT!

Is there a case when PermissionChecker API consumer might want to check staging group permissions and another case when the consumer wants to check live group permissions?

If so, then we probably need to review PermissionChecker uses and decide based on context?

Thank you.

**Comment by JorgeFerrer** [comment]
Hey Tomas,

On a first sight, the fix looks good to me. Basically what we have decided in the past is that for permissions of type INDIVIDUAL, the staging group should be checked since there can be changes done specifically in staging and not published to live yet. However for permissions of type GROUP (or GROUP_TEMPLATE) the live group should always be checked. 

However the code clearly does not express this decision in any way, so we should probably refactor it so that it does. By doing that we should also uncover other cases that, as you say, may also be currently left out.

**Comment by topolik** [comment]
Hi Jorge, thank you for the answer, frankly, I'm more confused then before
:)

> for permissions of type INDIVIDUAL, the staging group should be checked
since there can be changes done specifically in staging and not published
to live yet.

INDIVIDUAL permissions don't relate to groups in general?!

Do you mean checking INDIVIDUAL permission of a group itself? For example:
the check if "user has permission to MANAGE_LAYOUTS of the group" should be
applied always on the staging group?

> However for permissions of type GROUP (or GROUP_TEMPLATE) the live group
should always be checked

So do you mean, when retrieving roles available for a user, we should
always get the roles from LIVE group?

There is a funny scenario in this configuration, when checking a group for
some permissions:
- INDIVIDUAL scope .. retrieve Staging group roles
- GROUP(_TEMPLATE) scope ... retrieve LIve group roles

---

So that implies we should do site-roles assignment for user always only on
live group.

I tried site membership UI in control panel to know. It displays the same
roles assignment for both staging and live ... and it is LIVE GROUP
assignments (site member, site admin, ...) ... looks correct. But when I
select staging group and update the member ship, it's written into database
with staging groupId, but UI still displays old information from live
group?! Bug?

What about teams? When I create a team on staging, it's assigned staging
group id. Are teams propagated then?

So I'm confused what is the correct behavior.

Thank you.


-- tom +

**Comment by topolik** [comment]
I see, the "funny" scenario is what we have in AdvancedPermission.hasPermission(): https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/security/permission/AdvancedPermissionChecker.java#L576-L583

If primKey is staging group (INDIVIDUAL) we take live group for GROUP(_TEMPLATE) scope.
```java
				if (group.isStagingGroup()) {
					if (primKey.equals(String.valueOf(groupId))) {
						primKey = String.valueOf(group.getLiveGroupId());
					}

					groupId = group.getLiveGroupId();
					group = group.getLiveGroup();
				}
```

But it works only in case the provided groupId is staging. When we send `hasPermission(liveGroupId, liveGroupPrimaryKey)` this `if` block won't work as we want ... have staging group for INDIVIDUAL scope roles.

**Comment by topolik** [comment]
For the record, Ray answered that all permission related operations should be done on Live groups.  Staging groups are only to hold content.

**Comment by JorgeFerrer** [comment]
Hey Tomas, 

I'm sure what Ray meant is correct, but be careful with what you interpret. As you say staging holds content, which have (individual) permissions, those are set in live and should be checked there when the Admin is on staging and when publishing it should be propagated. 

I think we should document all this in a more formal way to avoid this headaches over and over.  Could you Stat that document based on what you have found out so far? 

I can help you out once I get back next week

**Comment by topolik** [comment]
Thank you for all your hints, please see https://github.com/rotty3000/liferay-portal/pull/984.

**Pull request closed without merging**
