### PR TITLE
[TECHNICAL-SUPPORT] LPS-87050

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by topolik** [comment]
Hi @jonathanmccann, I'm sorry but this is wrong, the back url can be a javascript.

**Comment by jonathanmccann** [comment]
@topolik Thank you for reviewing this pull. Did you have any ideas as to how to validate a redirect URL and also allow Javascript? Also, what is the reasoning behind allowing Javascript as a redirect for the back URL?

**Comment by jonathanmccann** [comment]
@topolik Are you looking for something like this?

https://github.com/jonathanmccann/liferay-portal/commit/38dc091cdb0c57c2ce3b1bb3e56f956caf74244f

This mirrors the logic in https://github.com/liferay/liferay-portal/blob/7.0.5-ga6/portal-web/docroot/html/taglib/ui/tabs/start.jsp#L74-L76 and allows for Javascript back URLs like https://github.com/liferay/liferay-portal/blob/7.0.5-ga6/portal-web/docroot/html/taglib/ui/error_header/page.jsp#L23-L26

If you want to go that route I can send that to you and make sure all our instances of `javascript:history.go(-1)` follow the same format of having or not having a semicolon.

**Comment by topolik** [comment]
Hi @jonathanmccann,

yes, that would be a way!

Also please find and fix inconsistencies similar to these:
* Using StringPool.BLANK to hide the back URL: https://github.com/topolik/liferay-portal/blob/36f29de2e4c2eabe5012876c6ba44713311f4bb0/modules/apps/opensocial/opensocial-portlet/docroot/admin/edit_gadget.jsp#L58
* Double escaping https://github.com/topolik/liferay-portal/blob/f554d5638209b59f6099d173b1122218df9af045/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/edit_structure.jsp#L191

Thanks!

**Pull request closed without merging**
