### PR TITLE
LPS-59485 User with permission to add user group cannot add one

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-59485](https://issues.liferay.com/browse/LPS-59485).<br><br>Hey Tomas, this issue occurs basically any time we use `permissionChecker.hasPermission` and pass in a primaryKey of 0 or the companyId (for example, [InlineSQLHelperImpl.java#L534-L535](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/security/permission/InlineSQLHelperImpl.java#L534-L535) or [UserGroupPermissionImpl.java#L32](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/permission/UserGroupPermissionImpl.java#L32) when creating a user group).  Is there a better approach to this, or is this what we need to do with all our entities?
/cc @pei-jung @jorgeferrer @rotty3000

### CODE REVIEW

**Comment by topolik** [comment]
Hi @drewbrokke,

I like this approach!

I think we need this hasPermission(groupId, name, action) method in PermissionChecker. 

As you found, currently we use everything for the primaryKey, 0, companyId, groupId, portlet name, and perhaps other things, which no longer works with the SCOPE_INDIVIDUAL check and we have a custom initialization blocks for when there is no SCOPE_INDIVIDUAL resource permission available.

However, this will require changes also to other places so probably I create a new pull request and base it on yours, if you don't mind.

Thanks.

**Comment by drewbrokke** [comment]
Hey @topolik!  I actually pulled this commit from a fix that is adding the new hasPermission check to PermissionChecker :) I'll go ahead and send you the pull of what I have.

**Comment by topolik** [comment]
I see, thanks Drew.

**Comment by topolik** [comment]
Just a question: you closed this pull, will #213 fix also this LPS-59485?

**Comment by drewbrokke** [comment]
No, #213 will not fix this issue. I am actually doing a separate fix that
makes sure all *ServiceImpl fetch methods check for null (as with
OrganizationServiceImpl.fetchOrganization). I'll be sending it to Brian
tomorrow. It will also fix the failing tests on #213.

On Tuesday, November 3, 2015, Tomáš Polešovský <notifications@github.com>
wrote:

> Just a question: you closed this pull, will #213
> <https://github.com/topolik/liferay-portal/pull/213> fix also this
> LPS-59485?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topolik/liferay-portal/pull/207#issuecomment-153623178>
> .
>


-- 
--
Drew Brokke
Software Engineer
Liferay, Inc.

*Liferay Symposium North America*
November 16-17, 2015 | Chicago, IL
CFP is now open! | www.liferay.com/northamerica2015

**Comment by drewbrokke** [comment]
Closing because I am making changes to many other ServiceImpl classes per Brian's request <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
