### PR TITLE
OAUTH2-173 Assign scopes UI should group like description AssignableScopes

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by csierra** [comment]
hey @stian-sigvartsen @topolik, 
it looks like that test failure is real: https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/223546//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog

looks like the content of the file is incorrectly escaped.

**Comment by csierra** [comment]
I have been talking with guys at the office and this might have been caused by Brian...

**Comment by topolik** [comment]
Closing, won't fix. We don't want to group scopes by translation.

**Pull request closed without merging**
