### PR TITLE
LPS-61340 Add the new configuration metadata

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@topolik I'll process this PR. Jorge sent it to our team as training for new annotations metadata cc/ @mikakoivisto

**Comment by topolik** [comment]
Thanks @stian-sigvartsen!

**Comment by stian-sigvartsen** [comment]
Pushed to Brian. See brianchandotcom/liferay-portal/pull/33619

**Comment by topolik** [comment]
Closing, already merged. Thank you.

**Pull request closed without merging**
