### PR TITLE
[TS] LPS-92818

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-92818

From @jrao

> Add supported signing algorithms configurable property and parse algorithms from property

I'm not entirely sure why these changes didn't produce a version increase, but the tests don't seem to pick up on it.  Please let me know if you have any questions for me, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@ChrisKian 

`OpenIdConnectProviderConfiguration.java` is not exported from the module, so it doesn't hurt semver.

**Comment by lipusz** [comment]
I'm not sure if it's an issue: you should specify the `discoveryEndPoint` which then will be used by the implementation to fetch the required info about the provider, for example https://accounts.google.com/.well-known/openid-configuration for Google.

When it's set, it works without issues (see for example https://grow.liferay.com/learn/OpenID+Connect+in+7.1+Skill+Map#Add-Google-as-OpenID-Connect-Provider-to-DXP).

Isn't mandatory to give? @ChrisKian  @jrao 

/cc @topolik

**Comment by topolik** [comment]
Hi guys, this seems to duplicate https://github.com/stian-sigvartsen/liferay-portal/pull/147

Can please sync with @cleydyr? 

/cc @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
Some thoughts...

* I think we should merge the language keys / translations from this pull into stian-sigvartsen#147 .
* The defensive programming (checking for null array reference) in this pull is unnecessary because the metatype will not return null
* It's useful for metatype to provide a default signing algorithm of RS256 (see stian-sigvartsen#147) as per the translations in this pull

**Comment by stian-sigvartsen** [comment]
//cc @cleydyr @ChrisKian @jrao

**Comment by jrao** [comment]
> I'm not sure if it's an issue: you should specify the `discoveryEndPoint` which then will be used by the implementation to fetch the required info about the provider, for example https://accounts.google.com/.well-known/openid-configuration for Google.
> 
> When it's set, it works without issues (see for example https://grow.liferay.com/learn/OpenID+Connect+in+7.1+Skill+Map#Add-Google-as-OpenID-Connect-Provider-to-DXP).
> 
> Isn't mandatory to give?

Hi @lipusz , I think it isn't mandatory to provide the discovery endpoint. Did you see the original use case? https://issues.liferay.com/browse/LPP-33378

**Comment by jrao** [comment]
@topolik @stian-sigvartsen Yes, this does duplicate https://github.com/stian-sigvartsen/liferay-portal/pull/147. I will send a follow-up PR with the language keys and anything else we need that wasn't included in @cleydyr's PR.

**Comment by lipusz** [comment]
Hey @jrao 

Please coordinate with @cleydyr and @stian-sigvartsen  instead and make sure everything is included in one PR under one LPS.

See https://github.com/brianchandotcom/liferay-portal/pull/70472#issuecomment-478578804.

**Comment by jrao** [comment]
@lipusz Will do.

**Comment by stian-sigvartsen** [comment]
Discussed with @jrao and he will combine the two pulls and send to me for review.

**Comment by jrao** [comment]
sent https://github.com/stian-sigvartsen/liferay-portal/pull/148

**Pull request closed without merging**
