### PR TITLE
LPS-72675

### PR DESCRIPTION
**Pull request by samuelkong**
Hi Tomas,
Can you take a look at my changes before I send to Brian. Thanks.

Doesn't affect FreeMarker templates

### CODE REVIEW

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/49136

View just my changes: https://github.com/topolik/liferay-portal/compare/samuelkong:e67706cb27...fa72b50419
View total diff: https://github.com/topolik/liferay-portal/compare/2e7e268a05...fa72b50419

**Comment by topolik** [comment]
It does affect FreeMarker templates. Fixed and sent to Brian. Thanks.

**Comment by samuelkong** [comment]
FreeMarker is affected in that there's information disclosure. But I don't think you can change the value of the variables from FreeMarker.

**Comment by topolik** [comment]
Please see my comment in the LPS. You cannot change values but access API not available/published to the freemarker context.

**Pull request closed without merging**
