### PR TITLE
LPS-55586

### PR DESCRIPTION
**Pull request by mikakoivisto**
Hey Tomas, I've added two classes that are required for using settings api for each service with configuration class. Now I think in order for the rest of the auto logins to have their own configuration class I think they will need their own SERVICE_NAME. You'll probably need to refactor them into their own package to follow the pattern of using package as the SERVICE_NAME. I think we should also move request.header.auth.hosts.allowed to configuration so that it can also be configured per portal instance basis from UI. Other than that looks like you applied the settings api correctly.

### CODE REVIEW

**Comment by mikakoivisto** [comment]
ci:retest

**Comment by topolik** [comment]
Hi @mikakoivisto, thanks for the PR, but I don't see the new classes you mentioned. Did you add them to the commit?

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Thanks Mika!

I'll completely refactor it into the new packages then.

**Comment by mikakoivisto** [comment]
It’s this commit https://github.com/mikakoivisto/liferay-portal/commit/04aec8ac95776e226b65ce4ee450ff930991ddfc the two classes under settings package.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/27229. Thanks!

**Pull request closed without merging**
