### PR TITLE
[TECHNICAL SUPPORT] LPS-79425

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-79425 

The user full DN from LDAP is returned by binding.getNameInNamespace() and we use it to query the assigned groups in LDAP.
In case of having a user full DN with special characters encoding in hex way (ex '\2c' instead of '\,') we are having problems in the LDAP query.

Using javax.naming.ldap.LdapName we can force all encoded special characters to be rewritten to the simple mode: \xx to \c and we avoid all query issues.

This hex encoding is only reproduced in case of using OpenLDAP, but if you review LDAP RFC both escape options are correct.

For more information, see LPS description and LDAP RFC https://docs.ldap.com/specs/rfc4514.txt

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @topolik 
Do you have any update about this pr?

Thank you

**Comment by topolik** [comment]
Hi @jorgediaz-lr, looking into it.

**Comment by jorgediaz-lr** [comment]
thanks!

**Comment by jorgediaz-lr** [comment]
Hi @topolik,

Did you review the pull request?

Please, tell me in case you have any question

**Comment by jorgediaz-lr** [comment]
Hi @topolik 

**Important:** I have added commit https://github.com/topolik/liferay-portal/pull/500/commits/8321fcd0f21b166dd5e6af09bbac4143693d6f26 because the number of backslashes in previous commit were incorrect.

The reason of changing escapeValue(...) logic is because I did some testing with the characters in RFC-4514:  `'"', '+', ',', ';', '<', '>',  and '\'` and I detected that in case of having a user with `'"'   or '\'`  in his name, the ldap group query didn't work.

In order to fix the query, it was necessary to escape that characters, so I have to escape following chars:
```
  \\ => \\\\ 
  \" => \\"
```

The tricky part is in java we have to escape again the baskslash and " characters:
So for each \ and " we have to add an additional \ . Final replacements are:
```
  \\\\ => \\\\\\\\ 
  \\\" => \\\\\"
```

**Comment by topolik** [comment]
Hi @jorgediaz-lr,

thank you. It would deserve a test, the backslashes are tricky. Can you please create a test for it? It would also make the LDAP escaping more clear.

Can we make a general purpose tool to escape LDAP queries? I guess there are more places like this one.

**Comment by jorgediaz-lr** [comment]
Hi @topolik 

I am going to create a test for **escapeValue** method. I will send you the pull request.

About
> Can we make a general purpose tool to escape LDAP queries? I guess there are more places like this one.

I didn't find this case of escaping the fullUserDN in other place, I think it is not necessary to apply this change in any other place.
Nevertheless, I think creating that general purpose tool it is out of the scope of this **bug** LPS ticket and it is not a task for Support department. I am going to create a new **story** LPS ticket with this requirement.

Regards,
Jorge Díaz

**Comment by topolik** [comment]
Thank you very much @jorgediaz-lr!

**Comment by jorgediaz-lr** [comment]
following pr https://github.com/topolik/liferay-portal/pull/505

**Pull request closed without merging**
