### PR TITLE
LPS-64815 - Extraction using Templates

### PR DESCRIPTION
**Pull request by martamedio**
_FreeMarker solution:_ Like you suggested, I wrap in an object the BeanModel used by the library. According to the official documentation, there is no way to return empty string without using reflection to change the original object (CompanyImpl), so I have raised an exception when the template tries to print a restricted property.

_Velocity solution:_ I have followed the same process that already exists for class restriction

About the configuration syntax, see previous PR: https://github.com/topolik/liferay-portal/pull/673

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/martamedio/liferay-portal/pull/67

View just my changes: https://github.com/topolik/liferay-portal/compare/martamedio:098a78e575...c3a37552b9
View total diff: https://github.com/topolik/liferay-portal/compare/fd98fdbf64...c3a37552b9

**Pull request closed without merging**
