### PR TITLE
LPS-122726

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-122726

### CODE REVIEW

**Comment by holatuwol** [comment]
Resend of https://github.com/topolik/liferay-portal/pull/850

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:forward

**Comment by lipusz** [comment]
Triggering forward as it has already been approved by Tomas, it's just committed under a new ticket.

**Pull request closed without merging**
