### PR TITLE
LPS-64200 Use standard success message taglib instead of custom code

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Tomas, 

I applied this change because I thought it was very inconsistent UI with the rest of the portal. Can you please review carefully?

thanks a lot!!

### CODE REVIEW

**Comment by topolik** [comment]
Hi Julio, does this fix https://issues.liferay.com/browse/LPS-64115?

**Comment by juliocamarero** [comment]
Nope, that bug is fixed already by a 2 lines css change that we already sent to Nate and Brian :)

However, while fixing that I saw this code and I couldn't help updating it since this had been like this since 2008  :)

This code just uses all the new taglibs and mechanisms (it looks much nicer) but the behavior doesn't change at all.

**Comment by topolik** [comment]
Thanks Julio! :)

However, I think I should not send this to Brian, this is not anything critical that must go to 7.0.

Please correct me if I'm wrong.

**Comment by juliocamarero** [comment]
I agree, it's not critical. However, not sending this now will make it very hard to release it in the next future in a module, since this needs to change portal-web itself :(

How would you feel about sending the infrastructure changes but not applying it to login? That way, we can apply to the login module in a future release...

**Comment by topolik** [comment]
Hehe, that's the thing. It's the infrastructure changes that I'm afraid of, because I don't understand that part enough to catch possible regressions.

If it would be only login portlet then it's fine, no big impact :(

**Comment by juliocamarero** [comment]
Thanks a lot for your concerns, Thomas. I agree.

Since the taglibs belong to the UI infrastructure team, I have sent the infrastructure changes to them so that they can make a decssion. I haven't changed anything in the login portlet: https://github.com/jbalsas/liferay-portal/pull/476

Thanks!

**Comment by topolik** [comment]
Thanks Julio!

**Pull request closed without merging**
