### PR TITLE
LPS-68984 Do not reject view action on omni-admin if the view action is performed by non-omni-admins. Also, for normal company admins, we do not restrict actions from others on them. Just like what we did in ee-6.2.X

### PR DESCRIPTION
**Pull request by rotty3000**
I'm pretty ok with the change, but wanted @topolik to see it before pushing upstream. If you're ok Tomas, could you push this to Brian?

### CODE REVIEW

**Comment by topolik** [comment]
Hi @zxdgoal, 

I don't understand that. 

What do you believe should be the correct behavior, to see or to not see portal admin? Seems https://issues.liferay.com/browse/LPS-50953 and this fix goes against each other, both created by you.

By this you are reverting back:
* https://issues.liferay.com/browse/LPS-29008 for company admins 
* and https://issues.liferay.com/browse/LPS-50953

Can you please clarify or did I miss something?

Thanks

**Comment by zxdgoal** [comment]
Hey Tomáš 

LPS-29008 should be fine as its fix is still there after my changes in this pr,https://github.com/liferay/liferay-portal/commit/fb398cd26a5fff9b5efe5f614857dcb1891c5b52#diff-0

For LPS-50953, I have to say it is wrong.

User actions on portal admins(not onmi-admin) should be granted if he has proper permission.

For example, if there is a user has a permission to VIEW members's personal information on a site, he should be able to his portal admin's info, shouldn't he?

LPS-50953 was created because I misunderstood LPS-50147, which is talking about forbidding users to be exposed to user from other instances which is another thing. I thought admins should not be exposed to any regular users(not admins), which is wrong.

Thanks
John.

**Comment by topolik** [comment]
Hi John,

I see, thank you.

Sorry I was wrong with the LPS-29008. The problem this will reintroduce is https://issues.liferay.com/browse/LPS-50147. Not on master where we have different mechanisms to check that but on 6.2/older..

Is it possible to remove just the VIEW from the protected actions or do we need to remove company admins from there too?

Thanks.

**Comment by zxdgoal** [comment]
Hey Tomáš

LPS-50147 will not be re-introduced because we check the companyid when checking permissions.

Even if I reverted the code in this pr, a user cannot perform actions on users from other instances and we will get an error like this:
```
 java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=37627, name=com.liferay.portal.kernel.model.User, primKey=34979, scope=4}
java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=37627, name=com.liferay.portal.kernel.model.User, primKey=34979, scope=4}
```
So, in fact, LPS-50147 was talking about leaking users across portal instances, which does not mean admins (not omni-admin) should be treated specially.

The fix of LPS-50147 has never been commit to 6.2.x, so 6.2 is not related to this pr.

> Is it possible to remove just the VIEW from the protected actions or do we need to remove company admins from there too?

So, image we have a user with permission to update users on his portal, Should he be able to update his    company admins?

My vote is yes. Company admins are still normal users. The admin role can be assigned to any users. It is not that reasonable to lock these users from being updated by others.

What do you think?

Thanks
John

**Comment by topolik** [comment]
Hi John,

thanks for all the effort and comments!

> With the fix of this pr, a user still cannot perform actions on users from other instances and we will get an error like this:
`java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=37627, name=com.liferay.portal.kernel.model.User, primKey=34979, scope=4}`

Yes, I know. On master / DXP it's fixed. But on not on 6.2.

> So, in fact, LPS-50147 was talking about leaking users across portal instances, which does not mean admins (not omni-admin) should be treated specially.
> The fix of LPS-50147 has never been commit to 6.2.x, so 6.2 is not related to this pr.

BUT the code is there! 

For 6.2 and older it was given a different LPS-64970, please see https://issues.liferay.com/browse/LPS-64970?focusedCommentId=759856&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-759856

So, as I mentioned, this change is fine for master but will reopen the problem on 6.2, or does this bug affects also older versions?

Thanks.

**Comment by zxdgoal** [comment]
Hey Tomas

If the changes affect 62, we should not backport the changes to 62, until we find the correct way to fix LPS-64970.

For master/DXP, my changes should be safe.

What do you think?

John.

**Comment by daledotshan** [comment]
Hey Tomas,
Do yo still have any concern about john's fix? After I talked about this fix and he said we fix this issue for 6.2..x individually

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/45378

View just my changes: https://github.com/topolik/liferay-portal/compare/rotty3000:751b10635e...7299ab9fdd
View total diff: https://github.com/topolik/liferay-portal/compare/90206a683e...7299ab9fdd

**Pull request closed without merging**
