### PR TITLE
OAUTH2-243 Apply ScopeMatcher before and after - avoid size() + configurable

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by topolik** [comment]
This is still valid, right?

**Comment by stian-sigvartsen** [comment]
@topolik yes I don't think this is fixed or relates to any other issue we have discussed recently

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/69254

View just my changes: https://github.com/topolik/liferay-portal/compare/stian-sigvartsen:03ff548404...22a5800a58
View total diff: https://github.com/topolik/liferay-portal/compare/4dda6fa7af...22a5800a58

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/69255

View just my changes: https://github.com/topolik/liferay-portal/compare/stian-sigvartsen:03ff548404...80a04983d9
View total diff: https://github.com/topolik/liferay-portal/compare/4dda6fa7af...80a04983d9

**Pull request closed without merging**
