### PR TITLE
TEST for TLS updates for petra json ws clent module

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Tomas, this test works if executed in IntelliJ, but it fails if executed via gradle (command line). I need help to figure out what prevents HTTPS server from running in gradle environment. Can you help me please?

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Igor, @igorbeslic 

I'm looking at the related changes you made to `BaseJSONWebServiceClientImpl.java` in https://github.com/liferay/liferay-portal/commit/a56115bd962e1918eb2c91448010a47708ee26f0 and I got question: would it be possible to update the code to consider the `https.protocols` system property instead of hard-coding 1.1 and 1.2?

Similar to what we did for HttpImpl and LicenseUtil:
https://github.com/liferay/liferay-portal/commit/6dba32960453c96b40b92c634adf34a2cc9076c5
https://github.com/liferay/liferay-portal/commit/845350c137eb527735a5396b480c35b70704383d

In that case, since we're using apache httpclient at both places, we went with `SSLConnectionSocketFactory.getSystemSocketFactory()` which will consider the two related system properties:
`https.protocols` and `https.cipherSuites` under the hood so it'll honor the settings of the underlying JVM.

**Comment by igorbeslic** [comment]
HI @lipusz let me check it. Petra json ws... is stand alone module - it has no any Liferay dependencies, and can be used in any other java application.
I'll check your links and try to apply changes.

Thank you very much!!!

**Comment by lipusz** [comment]
>it has no any Liferay dependencies, and can be used in any other java application.
Yeah, that's why I though it could make sense to support whatever is set in the underlying system. Thanks Igor! :+1:

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/igorbeslic/liferay-portal/pull/30

View just my changes: https://github.com/topolik/liferay-portal/compare/igorbeslic:66c39bf2e3...9c0399f5f8
View total diff: https://github.com/topolik/liferay-portal/compare/06cba80735...9c0399f5f8

**Pull request closed without merging**
