### PR TITLE
LPS-107063

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by yxingwu** [comment]
Hi @topolik ,
It's just a reminder.
Based on [the comment](https://issues.liferay.com/browse/LPS-107063?focusedCommentId=2109557&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2109557) from Tibor. The Users and System Management team also need to review this PR. After you review, if it's ok, please send the PR to the Users and System Management team.

Thanks.

**Comment by yxingwu** [comment]
ci:retest:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hello Tomas, @topolik 

I was wondering if you have the time to proceed with this review.

Thanks,
Tibor

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/pei-jung/liferay-portal/pull/607

View just my changes: https://github.com/topolik/liferay-portal/compare/yxingwu:78a5f4a89e...52884d1152
View total diff: https://github.com/topolik/liferay-portal/compare/60df34d7b2...52884d1152

**Pull request closed without merging**
