### PR TITLE
[TS] LPS-93824 Usages of forwarded host HTML header are unsafe

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-93824

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by topolik** [comment]
Hi @NorbertKocsis, did you consider using escapeRedirect? Why did you chose just using isValidPortalDomain, isn't it the same?

Thanks.

**Comment by NorbertKocsis** [comment]
Hi,

isValidPortalDomain seemed a better fit to me as escapeRedirect is more expensive, but we could go with escapeRedirect also.

Br,
Norbert

**Comment by topolik** [comment]
Hi @NorbertKocsis,

and this does fix the issue? Because in default configuration isValidDomain() returns with no checks.

**Comment by NorbertKocsis** [comment]
Hi,

Well if virtual.hosts.valid.hosts is set it resolves the issue, but if we want to consider leaving it as default escapeRedirect might be a better choice.

Br,
Norbert

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/72047

View just my changes: https://github.com/topolik/liferay-portal/compare/NorbertKocsis:7fdb0c75c1...25f060f629
View total diff: https://github.com/topolik/liferay-portal/compare/cdbff03ace...25f060f629

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/72048

View just my changes: https://github.com/topolik/liferay-portal/compare/NorbertKocsis:7fdb0c75c1...ce62964853
View total diff: https://github.com/topolik/liferay-portal/compare/cdbff03ace...ce62964853

**Pull request closed without merging**
