### PR TITLE
[TECHNICAL SUPPORT]LPS-94128 allow any valid url

### PR DESCRIPTION
**Pull request by linolaoj**
https://issues.liferay.com/browse/LPS-94128
https://issues.liferay.com/browse/PTR-810

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/71844

View just my changes: https://github.com/topolik/liferay-portal/compare/linolaoj:e1b76206de...575aff0f55
View total diff: https://github.com/topolik/liferay-portal/compare/b7b64d765f...575aff0f55

**Pull request closed without merging**
