### PR TITLE
LPS-78338 Apply Clay Management Toolbar in portal security service access policy web

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by topolik** [comment]
Hi @carloslancha, thanks for resending.

A question - how does the code know to check "SAPActionKeys.ACTION_ADD_SAP_ENTRY"? Or it doesn't check permissions?

Thanks.

**Comment by carloslancha** [comment]
Hey @topolik I missed that. Adding the following should fix it:

```
<clay:management-toolbar
....
showCreationMenu="<%= SAPPermission.contains(permissionChecker, SAPActionKeys.ACTION_ADD_SAP_ENTRY) %>"
...
/>

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/58508

View just my changes: https://github.com/topolik/liferay-portal/compare/carloslancha:d0755d1993...75026e67f2
View total diff: https://github.com/topolik/liferay-portal/compare/860aaac074...75026e67f2

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/58512

View just my changes: https://github.com/topolik/liferay-portal/compare/carloslancha:d0755d1993...6f6add80a5
View total diff: https://github.com/topolik/liferay-portal/compare/860aaac074...6f6add80a5

**Pull request closed without merging**
