### PR TITLE
LPS-61171

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:retest

**Comment by shinnlok** [comment]
ci:retest

**Comment by topolik** [comment]
Good catch! Thanks @shinnlok

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/33209
View total diff: https://github.com/topolik/liferay-portal/compare/7bbc3b4e84...a87bc6596b

**Pull request closed without merging**
