### PR TITLE
LPS-64364 return a correct error status when failed

### PR DESCRIPTION
**Pull request by samuelkong**
cc @arthurchan35

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:relevant

**Comment by topolik** [comment]
ci:test:sf

**Comment by topolik** [comment]
Hi @samuelkong  

what is the problem here? Is it only portlet configuration and CSRF? Or CSRF or security checks in general?

Thanks.

**Comment by samuelkong** [comment]
The ticket was created a long time ago and I don't remember exactly. But from what I recall, there's no security vulnerability here. It's just that when the the security scanner remove/edit the CSRF token, it still gets a 200 code so the scanner thinks there's a CSRF vulnerability. However, there's no vulnerability since we return a blank page. i.e., this ticket is just to make it easier for the stupid security scanner to realize there's no CSRF vulnerability by returning a more helpful error code.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/73952

View just my changes: https://github.com/topolik/liferay-portal/compare/samuelkong:38ab377a3c...097d3325bc
View total diff: https://github.com/topolik/liferay-portal/compare/db1f4571c6...097d3325bc

**Comment by topolik** [comment]
Thanks @samuelkong!

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/73953

View just my changes: https://github.com/topolik/liferay-portal/compare/samuelkong:38ab377a3c...4c870301d9
View total diff: https://github.com/topolik/liferay-portal/compare/db1f4571c6...4c870301d9

**Pull request closed without merging**
