### PR TITLE
[TECHNICAL-SUPPORT] LPS-65203

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-65203

/cc @eperezg

### CODE REVIEW

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Tomas,

Do you have time to proceed with this?

@topolik

**Comment by topolik** [comment]
Hi,

sure, get to it soon. Thanks

-- tom +

**Comment by lipusz** [comment]
thx, Tomáš! :+1:

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/39255
View total diff: https://github.com/topolik/liferay-portal/compare/5475581dc7...6798ed1e24

**Pull request closed without merging**
