### PR TITLE
LPS-81901 set configuration scope

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-81901

Resent from https://github.com/jonathanmccann/liferay-portal/pull/1641

> I believe these are incorrectly scoped. As this escalates in review I'm looking to hear from engineers on this and whether there are more system settings that are improperly scoped.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test

**Comment by topolik** [comment]
Hi @SpencerWoo, 

I believe these configurations were not meant to be shown in config admin UI at all. They are indeed company scoped but edited through Instance Settings portlet. Once they are saved from there, there's no way to update them in System Settings portlet. It doesn't make sense to show them there anymore from that point, it creates only confusion. 

Do you know if we can hide them?

**Comment by SpencerWoo** [comment]
Hi @topolik 

While COMPANY scopes don't propagate to influence Instance Settings when Instance Settings have been configured, I can think of two uses for them to remain

---
(1) They can still be used as the default setting; an example is creating a virtual instance.  Any created virtual instance will inherit the System Setting configuration by default.

(2) If Instance Settings aren't purposefully set, changing the System Setting does propagate.

**Comment by stian-sigvartsen** [comment]
With the recent addition of "reset" buttons on the Instance Settings SSO tabs, the System defaults are now very useful. @spencerwoo I've reviewed this pull on behalf of @topolik .

See brianchandotcom/liferay-portal/pull/60717

**Comment by topolik** [comment]
Thanks guys.

**Pull request closed without merging**
