### PR TITLE
LPS-64027 Site Role with General Permissions cannot access those options for those portlets in Site Administration

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-64027](https://issues.liferay.com/browse/LPS-64027).

@topolik @rotty3000 @jorgeferrer: this fixes the issue in the ticket but I'm hoping you can spot any potential regressions or vulnerabilities with this.  I'm still learning the permissions framework so any explanations of issues found would be helpful.  Thanks!

/cc @pei-jung

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey Drew,

Good job on this. I was only able to take a quick look, but I think the changes makes sense.

I hope one day we can make the permissions API more bullet proof, specially with regards to "optional" params such as the group Id.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/38973

View just my changes: https://github.com/topolik/liferay-portal/compare/drewbrokke:37b5533e29...bf76707495
View total diff: https://github.com/topolik/liferay-portal/compare/98d332c8fa...bf76707495

**Comment by topolik** [comment]
Hi @drewbrokke, almost perfect, thanks!

Please see https://github.com/brianchandotcom/liferay-portal/pull/38973/commits/bf7670749571b276a014798367ef8223fef59132

**Comment by drewbrokke** [comment]
Of course!  Thanks @topolik :)

**Pull request closed without merging**
