### PR TITLE
[TS] LPS-105881

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-105881](https://issues.liferay.com/browse/LPS-105881)

Hi Tomas,

I am sending this directly to you as Tibor is on holiday. I hope you can review it.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@istvansajtos Please add the [TS] designation to the subject. Thx!

**Comment by istvansajtos** [comment]
Thanks for catching it, @lipusz !

**Comment by lipusz** [comment]
Hi @istvansajtos 

Can you forward this to the Frontend team? The component belongs to them.

**Comment by istvansajtos** [comment]
Hi @lipusz ,

I've forwarded this to https://github.com/antonio-ortega/liferay-portal/pull/91 as per your request.

**Pull request closed without merging**
