### PR TITLE
[TS] LPS-68662 JAAS login loses GET parameters when using an auto-login hook

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-68662

Author: @NorbertKocsis
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased.

**Comment by lipusz** [comment]
Hi Tomas,

Did you happen to review this? :-)

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/44220
View total diff: https://github.com/topolik/liferay-portal/compare/bbc8e9a58f...ed5ead727f

**Comment by topolik** [comment]
Hi Tibor,

working on it right now.

-- tom +

**Pull request closed without merging**
