### PR TITLE
LPS-85112 null

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-85112](https://issues.liferay.com/browse/LPS-85112).<br><br>Hey Tomas, would you mind double-checking this for me?  Just in case there is something I had not thought of.<br><br>/cc @pei-jung @stsquared99 @alee8888 @lipusz

### CODE REVIEW

**Comment by topolik** [comment]
Hi Drew, why don't you just use *Service instead of *LocalService? https://github.com/topolik/liferay-portal/blob/a72173ef22cf1d11c5c5f1c7e60a6e86b8d96a2e/modules/apps/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/internal/portlet/action/UpdatePasswordMVCActionCommand.java#L186

**Comment by drewbrokke** [comment]
Hey @topolik, I had considered using the permissioned service, but the calls to `updatePasswordReset` and `updateReminderQuery` required the local service, so I opted to check the permissions at the top for all of them.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/63784

View just my changes: https://github.com/topolik/liferay-portal/compare/drewbrokke:a72173ef22...82b64937cd
View total diff: https://github.com/topolik/liferay-portal/compare/56c886f501...82b64937cd

**Comment by topolik** [comment]
Thanks @drewbrokke .

**Pull request closed without merging**
