### PR TITLE
[TECHNICAL SUPPORT] LPS- 38116 Unauthorized access to portlet_css (Look And Feel)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-38116

Hey Tomáš,

This is a forward port from 61x.

Regards,
-tibi

/cc @NorbertKocsis

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased to latest master.

**Comment by lipusz** [comment]
Hi Tomáš,

Have you had the time to review this?

**Comment by topolik** [comment]
Hi Tibor,

yes I quickly looked at it and want to make a small adjustment and try it :)

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/24902. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
