### PR TITLE
LPS-108642

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/csierra/liferay-portal/pull/646
View total diff: https://github.com/topolik/liferay-portal/compare/8bc1b2f838...eb334a95bd

**Comment by topolik** [comment]
Thank you, forwarded to @csierra, looks fine from a security perspective.

**Pull request closed without merging**
