### PR TITLE
LPS-84268

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-84268

Resent as per https://github.com/topolik/liferay-portal/pull/595#issuecomment-415763722

Let me know if there's any questions.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
@topolik any update on this one?

**Comment by topolik** [comment]
Hi,

I'm out of office, returning next week. Please send it to Carlos or Stian
if urgent.

Thanks!

(sent from smartphone)

-- tom +


Dne út 28. 8. 2018 20:47 uživatel Spencer Woo <notifications@github.com>
napsal:

**Pull request closed without merging**
