### PR TITLE
[TS] LPS-72090 XSS in Knowledge Base: Alert box is displayed when you print a knowledge base article with tittle "<svg onload=alert(5)>"

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-72090

Hi Tomas,

I ran `gradlew findSecurityBugs`, but to be honest, it's really hard to understand the report so instead I was just browsing the source for other place where we may not handle properly `kBArticle.getTitle()`.

Looks like get `content` is saved in an escaped form to the DB (probably the AntiSamy handles it) so I omitted those warnings too.

Cheers,
Tibor

/cc @ugurcancetin

### CODE REVIEW

**Comment by lipusz** [comment]
Forwarded to https://github.com/topolik/liferay-portal/pull/434.
See my changes: https://github.com/lipusz/liferay-portal/commit/0ff33ef3628068ff7112ad544c72295ea1739d91

**Comment by topolik** [comment]
Hi @lipusz 

still working on it, there are lot of issues, trying to clear them all.

Content is not handled by AntiSamy and expects rich HTML so I add that.

**Comment by lipusz** [comment]
Thank you, Tomas!

**Comment by lipusz** [comment]
Hi Tomas,

Do you think you can forward this today or you may need some additional work?

Thanks for the update!

@topolik

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/48883

View just my changes: https://github.com/topolik/liferay-portal/compare/lipusz:0ff33ef362...62a10f57d4
View total diff: https://github.com/topolik/liferay-portal/compare/8410660876...62a10f57d4

**Comment by lipusz** [comment]
Thank you!

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/48901

View just my changes: https://github.com/topolik/liferay-portal/compare/lipusz:0ff33ef362...ef93d984be
View total diff: https://github.com/topolik/liferay-portal/compare/8410660876...ef93d984be

**Pull request closed without merging**
