### PR TITLE
OAUTH2-216 Authorization prompt displays different scope to what will actually be granted

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi Stian,

this still doesn't work, or doesn't work as I would expect :)

I create an app, assign SAP `OAUTH2_everything` profile, save app. Disable `OAUTH2_everything`. Show the authorization screen, it doesn't list the OAUTH2_everything, approve. Get token, it is granted with "everything".

**Comment by topolik** [comment]
Let's wait for OAUTH2-214 to merge first, can be hitting this issue

**Comment by topolik** [comment]
Uhm, still looks strange, will need to discuss it again.

**Comment by topolik** [comment]
Hi @stian-sigvartsen,

we still don't correctly display the scopes in "Scopes" edit screen. When I open the application scopes it shows "everything.readonly" as checked in both portal services and my sample app. But only portal services scope is granted in DB. When I submit the screen then we save both.

**Comment by stian-sigvartsen** [comment]
Hi @topolik . This would be the best behaviour we can hope for until we improve the "Scopes" edit screen. Ideally it should highlight the diff between what's currently stored in DB and new scopes that will be stored for existing selected scope aliases, if re-saved.

Do you think we need to improve that screen as part of this ticket?

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/63328
View total diff: https://github.com/topolik/liferay-portal/compare/ebaa9c3e3f...b6a0366b35

**Pull request closed without merging**
