### PR TITLE
LPS-54043

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-54043 This contains the api you designed and it's implementation using the SB service. I'm including the Access Control Policy separately but wanted you to take a look at this already

### CODE REVIEW

**Comment by mikakoivisto** [comment]
Oh and this is built on top of what I sent to Nate for review so those parts are still subject to change.

**Comment by mikakoivisto** [comment]
I added the access control policy also so you can see it. The only question I have is what do we do if no profile are set by what ever authenticated the remote user? Currently I'm allowing access.

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @mikakoivisto,

what's the difference between service-access-control-profile-service and service-access-control-profile-api modules? Do we need both?

**Comment by mikakoivisto** [comment]
It's the basic SB pattern. -service is impl and -api has the interfaces.

**Comment by topolik** [comment]
OK, I see.

And related to ServiceAccessControlProfileThreadLocal - do we need another thread local? Can't we just use AccessControlUtil to store it there?

**Comment by mikakoivisto** [comment]
Yeah, I think we could use that. I just wanted to keep everything separate but that seems like a logical place.

**Comment by topolik** [comment]
Why do we have the public API in portal-service? 

We are mostly extracting code from core and not adding new things inside :)

**Comment by topolik** [comment]
Btw. the access control policy impl looks good!

**Comment by mikakoivisto** [comment]
It’s there because all the other stuff is there too. When we move them these will also move to a module. I just wanted to keep it simple otherwise it won’t pass Brian’s review.

**Comment by topolik** [comment]
The question is why we need the public API in portal-service when we already have one in service-access-control-profile-api ?

**Comment by mikakoivisto** [comment]
They are different api’s.  service-access-control-profile-api  is part of the impl for the api in portal-service. Now I’m fine with eliminating completely the portal-service api and have everything use the SB generated api but as I understood we wanted a separate clean api.

**Comment by topolik** [comment]
The good thing is that a legacy plugin doesn't need to inclue any *-service.jar (or *-api.jar) and can use it right away. But if the plugin would need to initialize some policy then it would need it anyways. 

I don't know. Are you going to send it to somebody else for review after me?

**Comment by mikakoivisto** [comment]
It’s going to Brian next.

**Comment by topolik** [comment]
Closing, we need to merge it with Nate's updates..

**Pull request closed without merging**
