### PR TITLE
[TS] LPS-91113 Avoid extra DB calls when portlets undeployed

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/69515
View total diff: https://github.com/topolik/liferay-portal/compare/0a5bb51491...59c4bacac2

**Comment by topolik** [comment]
Thanks @marianoalvarosaiz

**Pull request closed without merging**
