### PR TITLE
LPS-79944 Include feed title back because it's used in DefaultSocialActivitiesDisplayContext

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @sergiogonzalez 

Your change breaks the URLs that comes from Liferay 6.2 that ends in **...activities/rss** so won't match with */rss/{feedTitle}* (in Liferay 6.2 feedTitle is a parameter of queryString)

If you want to add feedTitle to friendlyUrl, it is necessary to add a second rule.

Please reach me if you have any question.

**Comment by jorgediaz-lr** [comment]
Thank you @sergiogonzalez the new commit https://github.com/topolik/liferay-portal/pull/503/commits/76cccc19847c1ae087d799e2993d0f267f4b0b38 avoids the issue with old URLs from 6.2

@topolik about my change in https://github.com/topolik/liferay-portal/pull/503/commits/6e0eadac6ac56e843885a5ce87c0640956790e77 it is necessary to concatenate the queryString because digest uri sent from browser contains it.

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
Hi @topolik 

If you need some time in order to get the right, it is not a problem.

Nevetheless, Is it ok to send to customer a temporary hotfix with my changes?
(customer ticket is open from long time ago, and I would like to send them a solution)

Thank you,
Jorge

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/57601
View total diff: https://github.com/topolik/liferay-portal/compare/7ee5c88bcd...12b570fe9b

**Comment by topolik** [comment]
Hi @jorgediaz-lr,

so in the end what I came up was very similar to your fix so I sent Brian your one instead. :)

Thanks.

**Comment by jorgediaz-lr** [comment]
Thank  you, @topolik  😃 !

**Pull request closed without merging**
