### PR TITLE
LPS-79290

### PR DESCRIPTION
**Pull request by samuelkong**
@topolik 
Sending to you to review first. But someone on the Forms team should probably also review before going to bchan.

cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test

**Comment by samuelkong** [comment]
ci:retest

**Comment by topolik** [comment]
Hi guys,

shouldn't we move the configuration into `DDMGroupServiceConfiguration` for all DDM portlets? We have just one CSV exporter in data-mapping-io.

Other than that it looks fine. Thanks.

**Comment by yxingwu** [comment]
Hi @topolik ,

Thank you for your comment.

But, I found that dynamic-data-lists-web and dynamic-data-mapping-form-web, both of them, have the "Default Display View" configuration. They config it separately. so I think we  can config "CSV" separately too. we don't need move it into "DDMGroupServiceConfiguration" for all DDM portlets.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/rafaprax/liferay-portal/pull/491
View total diff: https://github.com/topolik/liferay-portal/compare/312ff867b6...9c58c5bab9

**Pull request closed without merging**
