### PR TITLE
LPS-55941

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @topolik,

I made some changes with the exceptions and I also had to update the UI a bit since Google changed it between the time of the first pull request and this one. If you are good with this pull, it might be good to send it to someone in UI to have them review the changes for rendering the captcha without Javascript.

For the errors, I added a CaptchaConfigurationException to handle the cases where there is an error coming from reCAPTCHA. I left in the ReCaptchaException to handle the case where there are no errors but the validation still failed, which indicates that the verification was not passed and not a configuration issue.

Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
Hi @jonathanmccann,

I don't understand why we have now ReCaptchaException? When validation fails we have CaptchaTextException, isn't it a duplication?

Also it means that in portal core JSPs we still reference Captcha implementation class.

**Comment by topolik** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/736. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
