### PR TITLE
LPS-55941

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @jonathanmccann,

why do we need ReCaptchaException?

Thanks.

**Comment by jonathanmccann** [comment]
Hi @topolik,

I created that exception to be more explicit about what was happening. I thought that the CaptchaTextException would not accurately describe the issue since no text is inputted and the CaptchaException was not specific enough. That was one of the items though that I wasn't entirely sure about. Please see https://github.com/hhuijser/liferay-portal/pull/2360 for my questions/thoughts and let me know if you have any more questions about the pull.

Thanks!

**Comment by topolik** [comment]
I see. ReCaptchaException signalizes a server side error. I agree the CaptchaTextException is not the best one for it.

The thing is that when I see "reCAPTCHA verification failed" I think that there was a mistake on my side - entering wrong captcha text or so.

Also, ReCaptchaException is now referenced from portal JSPs which should not know about the captcha implementation.

Please can you rename the exception to CaptchaConfigurationException or something like this, or just use CaptchaException?

Can you please also change the message to tell user there is a server side problem only portal administrator can fix?

Thank you!

**Pull request closed without merging**
