### PR TITLE
LPS-59105  Stop sorting if the parameters have the same to mantain the same parameter array order

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by topolik** [comment]
Waiting for another PR :)

**Comment by robertoDiaz** [comment]
Hey Tomáš,

The fix is not as easy as we though due the compartor is not able to order
the fields by size and name

I think we need to group the parameters by name and compare and order this
groups by size

Im still working on this

**Comment by topolik** [comment]
Hi Roberto,

I think this fix already groups parameters by name!

Is really the root problem the order of values that has same name? On which line is the problem in the ADT?

Thanks.

**Comment by robertoDiaz** [comment]
This fix doesn't group by name in all the cases. if it works is accidentaly.

It groups them by name only if one of the repeated values is compared with
the other, but once we start grouping them by size we could not guarantee
this name comparation.

Today we don't work in Madrid, but tomorrow I'll fix this

2015-11-09 11:03 GMT+01:00 Tomáš Polešovský <notifications@github.com>:

> Hi Roberto,
>
> I think this fix already groups parameters by name!
>
> Is really the root problem the order of values that has same name? On
> which line is the problem in the ADT?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topolik/liferay-portal/pull/216#issuecomment-155016994>
> .
>



-- 
*Roberto Díaz*
Liferay Core Engineer


Liferay España y Portugal / Liferay Spain and Portugal
Tel. +34 917336343
www.liferay.com


Enterprise. Open Source. For Life.
Síguenos en  <http://www.facebook.com/pages/Liferay/45119213107>
<http://www.facebook.com/pages/Liferay/45119213107>
<http://www.twitter.com/%21/liferay_es>
<http://www.liferay.com/about-us/news>

Visit Us: www.liferay.com  |  Like Us: facebook.com/liferay  |  Follow Us:
twitter.com/liferay_es

*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Comment by topolik** [comment]
I see, you are correct. My tests worked because I used same size values! :(

**Comment by robertoDiaz** [comment]
See https://github.com/topolik/liferay-portal/pull/218

Now manual test are passing.

Let's see if the CI test pass as well.

2015-11-09 14:22 GMT+01:00 Tomáš Polešovský <notifications@github.com>:

> I see, you are correct. My tests worked because I used same size values! :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topolik/liferay-portal/pull/216#issuecomment-155059792>
> .
>



-- 
*Roberto Díaz*
Liferay Core Engineer


Liferay España y Portugal / Liferay Spain and Portugal
Tel. +34 917336343
www.liferay.com


Enterprise. Open Source. For Life.
Síguenos en  <http://www.facebook.com/pages/Liferay/45119213107>
<http://www.facebook.com/pages/Liferay/45119213107>
<http://www.twitter.com/%21/liferay_es>
<http://www.liferay.com/about-us/news>

Visit Us: www.liferay.com  |  Like Us: facebook.com/liferay  |  Follow Us:
twitter.com/liferay_es

*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Pull request closed without merging**
