### PR TITLE
[TECHNICAL SUPPORT] LPS-85148 Regular Expression in Password Policies is truncated to 75 characters

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-85148

/cc: @achaparro

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @topolik 

Do you have any update about this pull request?

Thank you

**Comment by topolik** [comment]
Hi @jorgediaz-lr,

didn't have time to look at it on Friday. It's on my radar :)

Thanks.

**Comment by jorgediaz-lr** [comment]
Thank you for the information :wink:

**Comment by jorgediaz-lr** [comment]
Hi @topolik 

Did you have any time to have a look to my changes?

In order to help a bit:
 - The customer wants to create a regular expression greater than 75 chars (default size for String fields)
 - So I am changing column type to "TEXTAREA"  (database level, from "VARCHAR(75)" to "STRING")

My changes:
   - I am changing field type in first commit https://github.com/topolik/liferay-portal/pull/606/commits/276cbe4199ebce121202080fa04823cadc70e392 in `portal-model-hints.xml`
   - Adding a upgrade process https://github.com/topolik/liferay-portal/pull/606/commits/aabc5227a25bdc60c81fe2adef9854e8797da6f1 in order to alter column type to new size.
   - Commits https://github.com/topolik/liferay-portal/pull/606/commits/4680d5556a53599b13360eb3a6654beee0465141 and https://github.com/topolik/liferay-portal/pull/606/commits/d99e9fe584eaaf5ce42701f54105f19682e55ae8 are autogenerated

Thank you

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/63068

**Comment by csierra** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
thank you @csierra

**Comment by csierra** [comment]
thanks to you... you did all the work :-)

**Pull request closed without merging**
