### PR TITLE
LPS-85179

### PR DESCRIPTION
**Pull request by jonathanmccann**
@topolik I made a change to the BasePersistenceImpl since it seems we should be returning the updated model. This allows the tests to pass but I feel wary of changing this method since it seems strange this issue would just now crop up.

Let me know what you think.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by topolik** [comment]
Hi @jonathanmccann,

so you actually found a whole family of bugs. I believe your last commit is correct. And searching though code base there are 699 possible places where we don't do anything with the `#update()` result. On many places it can be fine but on many places it's wrong. I'm trying to clear that out.

**Comment by jonathanmccann** [comment]
Wow, ok. Please let me know if there's anything I can do to help.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/63780
View total diff: https://github.com/topolik/liferay-portal/compare/307712c51b...24646d43e8

**Pull request closed without merging**
