### PR TITLE
[TS] LPS-94697 Handle Meta.Type.Password fields

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,
 were you able to take a look to this PR?
Kind regards.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/72632

View just my changes: https://github.com/topolik/liferay-portal/compare/marianoalvarosaiz:97eebd98e7...eeb0e17ca6
View total diff: https://github.com/topolik/liferay-portal/compare/6300a6edfe...eeb0e17ca6

**Pull request closed without merging**
