### PR TITLE
LPS-55621

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26687. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
