### PR TITLE
[TECHNICAL-SUPPORT] LPS-56446 Email message sent from Invitation portlet exposes the sender host's user name in the Message-ID header

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-56446

Hi Tomáš,

Checkout the description of the LPS to see how to overcome the regression (https://issues.liferay.com/browse/LPS-51143) on master in the invitation portlet to be able to test and the comments for details.

Regards,
Tibor

/cc @IstvanD

### CODE REVIEW

**Comment by lipusz** [comment]
"Message-Id" after the fix:
````HTTP
Message-ID: <invitation.1435055252695@events.liferay.com>
````

**Comment by lipusz** [comment]
Same tests failed for the original pull: https://github.com/lipusz/liferay-portal/pull/77#issuecomment-114144682

Looks unrelated.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Tom,

Did you happen to review this?

**Comment by lipusz** [comment]
Rebased

**Comment by topolik** [comment]
Hi Tibor, 

I'm sorry working on other things. I can process it next week, if possible.

By just looking at it it seems there can be a problem with message ID uniqness (https://en.wikipedia.org/wiki/Message-ID)

Two threads sending email at the same moment will create two emails with the same messageId.

Other than that I'm fine with it.

Thanks.

**Comment by lipusz** [comment]
Hi Tom,

I see your point.
Are thinking about to add some random salt instead of the long value of the
time? Do you want István to improve this part? If so, your remarks, hints
are always welcome.

Br,
Tibor

On Fri, Jun 26, 2015 at 8:25 PM, Tomáš Polešovský <notifications@github.com>
wrote:

> Hi Tibor,
>
> I'm sorry working on other things. I can process it next week, if possible.
>
> By just looking at it it seems there can be a problem with message ID
> uniqness (https://en.wikipedia.org/wiki/Message-ID)
>
> Two threads sending email at the same moment will create two emails with
> the same messageId.
>
> Other than that I'm fine with it.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topolik/liferay-portal/pull/172#issuecomment-115824361>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Comment by lipusz** [comment]
@topolik

On Mon, Jun 29, 2015 at 10:51 AM, Tibor Lipusz <tibor.lipusz@liferay.com>
wrote:

> Hi Tom,
>
> I see your point.
> Are thinking about to add some random salt instead of the long value of
> the time? Do you want István to improve this part? If so, your remarks,
> hints are always welcome.
>
> Br,
> Tibor
>
> On Fri, Jun 26, 2015 at 8:25 PM, Tomáš Polešovský <
> notifications@github.com> wrote:
>
>> Hi Tibor,
>>
>> I'm sorry working on other things. I can process it next week, if
>> possible.
>>
>> By just looking at it it seems there can be a problem with message ID
>> uniqness (https://en.wikipedia.org/wiki/Message-ID)
>>
>> Two threads sending email at the same moment will create two emails with
>> the same messageId.
>>
>> Other than that I'm fine with it.
>>
>> Thanks.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/topolik/liferay-portal/pull/172#issuecomment-115824361>
>> .
>>
>
>
>
> --
>
> *Tibor LIPUSZ*
>
> Senior Software Engineer @ TS
> Security SME, Subscription Services & Release, Global
>
>
> *Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
> Hungary
>
>  *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us: **facebook.com/liferay
> <http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
> <http://twitter.com/liferay>*
>
>
> * <http://twitter.com/liferay>*
>
>  <http://www.liferay.com>
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Comment by lipusz** [comment]
Hi Tomáš,

Did you happen to see my previous comments?

@topolik

**Comment by topolik** [comment]
Hi Tibor,

yes please, anything random.

Thanks.

**Comment by lipusz** [comment]
OK. Thank you, Tom.

@IstvanD: please, modify your solution by using a random salt instead of
time.

Thx.

On Tue, Jun 30, 2015 at 3:48 PM, Tomáš Polešovský <notifications@github.com>
wrote:

> Hi Tibor,
>
> yes please, anything random.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topolik/liferay-portal/pull/172#issuecomment-117190089>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Pull request closed without merging**
