### PR TITLE
LPS-66371

### PR DESCRIPTION
**Pull request by samuelkong**
This change will
* Prevent blog & MB drafts from saving if the user's session expires
* Prevent guest users from commenting

The portal should be secure by default, so admins that want these features should make the necessary changes.

`/document_library/edit_file_entry` this was originally for the flash uploader, which I don't think we use any more.

### CODE REVIEW

**Comment by topolik** [comment]
Hi guys, do we need the backup in `portal.properties`?

**Comment by topolik** [comment]
`/document_library/edit_file_entry` is used in portal but only together with PortletURL, it should already taken care of it.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/56337

View just my changes: https://github.com/topolik/liferay-portal/compare/samuelkong:05f41f8ad2...4d091e1464
View total diff: https://github.com/topolik/liferay-portal/compare/c60a551ceb...4d091e1464

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/56337

View just my changes: https://github.com/topolik/liferay-portal/compare/samuelkong:05f41f8ad2...4d091e1464
View total diff: https://github.com/topolik/liferay-portal/compare/c60a551ceb...4d091e1464

**Comment by samuelkong** [comment]
`/document_library/edit_file_entry` is definitely still used. What I meant is that it was added to 'auth.token.ignore.actions' because the flash uploader needed it. But it should be safe to remove from 'auth.token.ignore.actions' since we don't have the flash uploader.

As far as be the backup copy, it's not absolutely needed. It's just there to make it easier for customer to enable drafts and commenting if they want to have these features.

**Pull request closed without merging**
