### PR TITLE
LPS-90053

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:sf

**Comment by topolik** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by topolik** [comment]
@martamedio 
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/login/login-web/src/main/java/com/liferay/login/web/internal/portlet/action/LoginConfigurationActionImpl.java:71: error: cannot find symbol
     [exec] 				PropsValues.ADMIN_EMAIL_PASSWORD_SENT_BODY));
     [exec] 				           ^
     [exec]   symbol:   variable ADMIN_EMAIL_PASSWORD_SENT_BODY
     [exec]   location: class PropsValues
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/login/login-web/src/main/java/com/liferay/login/web/internal/portlet/action/LoginConfigurationActionImpl.java:77: error: cannot find symbol
     [exec] 				PropsValues.ADMIN_EMAIL_PASSWORD_SENT_SUBJECT));
     [exec] 				           ^
     [exec]   symbol:   variable ADMIN_EMAIL_PASSWORD_SENT_SUBJECT
     [exec]   location: class PropsValues
```

**Comment by martamedio** [comment]
Fixed at: https://github.com/topolik/liferay-portal/pull/753/commits/541f80d741c81e89a1bd62a363c0e808a036772d

Please, see: https://github.com/topolik/liferay-portal/pull/753

**Comment by martamedio** [comment]
Please, see: https://github.com/topolik/liferay-portal/pull/755

**Comment by martamedio** [comment]
Hopefully, the definitive one: https://github.com/topolik/liferay-portal/pull/756

**Pull request closed without merging**
