### PR TITLE
LPS-102777 Secure test LDAP connection command

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Tomas. I wasn't sure if it is acceptable to protect MVCRenderCommands like this. There are no other occurrences of this in the codebase. There are examples of Struts Actions and serveResource() examples of doing this.

Converting it to Struts seemed over engineering the fix. Converting to serveResource() seems slight more appropriate, but adds complexity because we're only interested in a text/html response. Additionally if we did convert then we should also convert the other test commands.

/cc @csierra @lipusz

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
The other LDAP tests seem also having the vulnerability.

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@stian-sigvartsen will you look into @arthurchan35 's comment in https://github.com/topolik/liferay-portal/pull/812#issuecomment-546799368?

**Pull request closed without merging**
