### PR TITLE
LPS-86233 PortletPreferences

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @topolik 
Thanks for helping review it.
The goal is to remove PortletPreferences of ownerId = 0, ownerType = 3, and plid = 0. Please see LPS-86233 and its child tickets for detail.

This pull may not pass all tests, but I want your reivew on the whole approach first.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by topolik** [comment]
@arthurchan35 The export failures look real

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
So wierd, the ci keeps reporting different failures that I could not reproduce locally.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Pull request closed without merging**
