### PR TITLE
LPS-54599 CSRF token is included in URL when a form submission fails

### PR DESCRIPTION
**Pull request by Preston-Crary**
In the case of a failed form submission sending a redirect would remove the form data.  So, instead I just move the token for forms.

### CODE REVIEW

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @Preston-Crary,

Alhough it's not working with multipart/form-upload requests I like the idea very much. 

I try to dig deeper to see if there is a simple fix for it.

**Comment by topolik** [comment]
I'm sorry, I have to close it.

I checked it also with @rotty3000, it's not possible to fix it this way. Portal cannot read request parameters that are in the upload request body (posting blog entry, message boards, web content, ...). 

There could be a way for built-in portlets but not for 3rd party portlets where the upload request parsing is done by the portlets themselves and portal has no knowledge about data inside the upload request. We could break existing customer portlets that use <aui:form>.

I firmly believe the only global solution in our situation are one-time tokens. This would fix everything and everywhere.

**Comment by Preston-Crary** [comment]
@topolik 
Sorry, I'm a little confused by your last statement.  What do you mean by "one-time tokens"?

Does this mean we must send a redirect in the PortletRequestProcessor and somehow serialize the form into the session?

**Comment by topolik** [comment]
No, this means we need to reimplement our CSRF implementation so that
p_auth token can be used only once
=> it doesn't matter if it leaks in URL or not, it has been already used

You can try that but it's not a bug fix. It deserves some research so that
we won't break anything. Let me know if you would like to implement it, I
would help you.


-- tom +

**Comment by Preston-Crary** [comment]
I would like to implement it, it sounds really interesting.  I'll do some initial research and email you when I've come up with a plan if that's alright with you.

**Comment by Preston-Crary** [comment]
https://github.com/topolik/liferay-portal/pull/139

**Pull request closed without merging**
