### PR TITLE
OAUTH2-214 Some further issues fixed

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Reviewed & squashed stian-sigvartsen/liferay-portal/pull/114 into a438574 .

Only issue I found with your changes was that Set.removeIf() was throwing UnsupportedOperationOperation because the Set provided by the caller was immutable. Fix in 
b9aeb6a

I also found that we weren't storing new ScopeAliasesLists as sorted because sorting was only done when fetching. Also we weren't stripping out empty string scope aliases passed to the updateScopeAliases by the MVCActionCommand occasionally, so we were unnecessarily creating ScopeAliases records at times.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
p.s. I tried to preserve some of your commits but it was difficult with all the moving of code between classes :(

**Comment by topolik** [comment]
Hi @csierra, this is one that you can look at if you find a time. Thanks.

**Comment by csierra** [comment]
a couple of remarks so far:
* Is it possible to create a test to show this problems? If so I believe we should create one. 
* it looks like the method `hasUpToDateScopeGrants` should not be public, because it looks it is checking the internal state of the model of that service. It looks to me we are missing an update method that should perform the check and optimize the operation if not needed? For the moment, and to make it more easily backporteable(?), I am moving the logic to the service update method and make `hasUpToDateScopeGrants` private. But for master I believe we should create an update method in the service with the same signature as the add method that would do the fetch and the check and invoke update or add depending on the result. I would say this is the pattern. 

What Do You Guys Think?

**Comment by csierra** [comment]
guys... please review https://github.com/stian-sigvartsen/liferay-portal/pull/117
that pull should be directly backporteable. I am going to send another one with an extra change for master

**Comment by csierra** [comment]
please see https://github.com/stian-sigvartsen/liferay-portal/pull/118 as well

**Comment by csierra** [comment]
ci:close

**Comment by stian-sigvartsen** [comment]
Hey @csierra.  Re. "Is it possible to create a test to show this problems? If so I believe we should create one." 

I created a test and sent in a separate pull, which @topolik returned to me at stian-sigvartsen/liferay-portal/pull/115 to be resent once the OAUTH2-214 is merged. The test is a full end-to-end TOCTOU test covering both the admin side and end-user consent side.

**Comment by csierra** [comment]
it would be great to have it here so we know that my changes did not break your changes

**Comment by stian-sigvartsen** [comment]
Agree. The reason it wasn't is because the tests cover several tickets :(

**Comment by stian-sigvartsen** [comment]
See csierra/liferay-portal/pull/446

**Pull request closed without merging**
