### PR TITLE
LPS-52750

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Tom,

Not quite sure about this fix... this is what Jonathan wrote:
The previous fix LPS-19866 used the current site to get a friendly URL to use in the impersonation URL. This led to the URL being random and dependent on who is doing the impersonating. In order to not reintroduce LPS-19866 but also allow for a static impersonation URL, I created a new portal property for a default impersonation URL

**Comment by topolik** [comment]
Hi @jonathanmccann,

I tried to understand the logic behind but I'm not sure if I get it right.

I see you basically reverted the fix for LPS-19866 and fixed it differently - using a static URL?

If so, can you please send a new pull request with "Revert ..." commits so that it's clear? Did you also test the regressions that were caused by LPS-19866?

Thanks.

**Comment by jonathanmccann** [comment]
Hey Tomáš,

I didn't do the "Revert" commit because there are other changes made on top of LPS-19866 and doing the revert via Gitk results in a merge conflict so I thought it would be cleaner to just do it like this. If you'd like me to do a manual revert of it though I can definitely do that.

I did test LPS-19866 and it still works properly after my fix has been made.

Thanks.

**Comment by topolik** [comment]
If you could revert the commits I think it would be the cleanest solution.

Looking into the history of the ticket (https://github.com/liferay/liferay-portal/commits/master/util-taglib/src/com/liferay/taglib/security/DoAsURLTag.java) there are 2 important tickets:
* https://issues.liferay.com/browse/LPS-20046
* https://issues.liferay.com/browse/LPS-27868

It seems both only fix regressions of the old LPS-19866:
* LPS-20046: https://github.com/liferay/liferay-portal/commit/22e1ef800bfc562306545e372df40358edc45752
* LPS-27868: https://github.com/liferay/liferay-portal/compare/445fed4834c2fce682ea413303e8d9b8656db86f...9588213a119502954be1ada5256b5385f3373aee

So for me it seems we can revert all these commits and clean it a bit, if possible:
lps-19866-and-regressions

Thank you.

**Comment by jonathanmccann** [comment]
Resent: https://github.com/topolik/liferay-portal/pull/120

**Comment by topolik** [comment]
Thank you. Please see https://github.com/hhuijser/liferay-portal/pull/2284

**Pull request closed without merging**
