### PR TITLE
Lps 55799

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26850. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Thank you @mtambara, good work.

**Comment by mtambara** [comment]
cc @shuyangzhou

**Pull request closed without merging**
