### PR TITLE
[TS] LPS-69762 Unable to include .tpl file in a layout template (regression)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69762

Hi Tomas,

Please see further details on the ticket. You'll know the background. ;-)

Thanks,
Tibor

----
Author: @ugurcancetin
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Test failures are not related to this fix.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Forwarded to https://github.com/stian-sigvartsen/liferay-portal/pull/55.

**Comment by topolik** [comment]
Thanks Tibor!

**Pull request closed without merging**
