### PR TITLE
[TECHNICAL-SUPPORT] LPS-86681

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by topolik** [comment]
Hi guys,

this is probably the proper place but the validation ("if" condition) must be more strict. This way it reopens the vulnerability again.

Example - when an attacker wants to keep the hijacked session open then all he needs to do is to send "doAsUserId" parameter with all his requests. Then the filter is ignored and session not invalidated.

We also need to check if actual impersonation happened, i.e. similar things like we do with ThemeDisplay.setRealUser in ServicePreAction.

Please resend.  Thank you.

**Comment by brianikim** [comment]
New pr: https://github.com/topolik/liferay-portal/pull/696

**Pull request closed without merging**
