### PR TITLE
LPS-97485

### PR DESCRIPTION
**Pull request by yxingwu**
Hi Tomas,
I am working on [LPS-97485](https://issues.liferay.com/browse/LPS-97485) , but I am not sure the solution is ok or not. So I send the PR to you and look forward to your suggestion.

Actually, I have another solution here:

1. Move the ModelPermissions to portal-impl and rename it to ModelPermissionsImpl
2. Create a ModelPermissions interface in portal-kernel and ModelPermissionsImpl implements ModelPermissions interface
3. Create new methods to create the instance of ModelPermissions (we'll use spring to do that.)

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi @yxingwu,

I'm afraid of breaking customers/3rd party code just by removing the possiblity to use it.

Maybe the solution is to fix again all existing places and create a new SF rule to use the factory?

**Comment by yxingwu** [comment]
Hi @topolik ,
It is ok to fix all existing places again and create a new SF rule to use the factory.
But it just fix in the` liferay-portal`. For our clients, we still can't  forbid the direct use of `ModelPermissions` class (Do you have any idea for this?).

**Comment by topolik** [comment]
Yes, that's it. We need to deprecate, not remove.

**Pull request closed without merging**
