### PR TITLE
LPS-59105 Control if they are equals

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci-retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by topolik** [comment]
Please see https://github.com/robertoDiaz/liferay-portal/pull/320. Thanks!

**Pull request closed without merging**
