### PR TITLE
[TS] LPS-108110

### PR DESCRIPTION
**Pull request by jonathanmccann**
@topolik,

The check that is being modified was introduced by LPS-72939 to return in the case of a relative URL. No other special characters seems to allow the redirects to occur so that is why only the backslash is being checked.

If you have any concerns or see a better way to resolve the issue please let me know.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/arthurchan35/liferay-portal/pull/60
View total diff: https://github.com/topolik/liferay-portal/compare/d798248382...6d9a82724a

**Comment by topolik** [comment]
Sent to @arthurchan35, he works on a vert similar issue - LPS-107195

**Pull request closed without merging**
