### PR TITLE
LPS-68220

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Not really sure how to test everything.  Can you double check my changes?  Thanks!

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/63350

View just my changes: https://github.com/topolik/liferay-portal/compare/Preston-Crary:c4aea8817f...3f251cc121
View total diff: https://github.com/topolik/liferay-portal/compare/149c735b16...3f251cc121

**Pull request closed without merging**
