### PR TITLE
LPS-46570 User cannot see existing templates and structures if they are given a created role

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-46570](https://issues.liferay.com/browse/LPS-46570).<br><br>/cc @rotty3000 @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by topolik** [comment]
@drewbrokke Please wait a bit, I'd like to fix the permission system next week. This ticket is related to things that @sammso did and we need fixes that protect whole codebase from similar ones. Otherwise we'll be fixing many issues again and again. 

There are also many duplicit tickets so I'd like to fix the root cause and then have the tickets retested to eliminate the duplicate ones.

Thanks!

**Comment by drewbrokke** [comment]
@topolik I'll just let you handle changes on this front moving forward.  Please keep me in the loop on any changes made so I can revisit and retest our tickets.  Let me know if there's anything I can do to help :)

**Comment by drewbrokke** [comment]
Hey @topolik it looks like this particular ticket is fixed already.  However, I think the change in this pull (or something like it) still needs to happen.  What is the status for this?

**Comment by topolik** [comment]
Hi Drew,

I think the fix for this ticket was different than what you sent.

However, what you sent still applies to other kinds of permission issues we
have, caused by the SCOPE_INDIVIDUAL check in resource permission. I have
it on my TODO and we will address it before 7.0 release.

-- tom +

**Comment by drewbrokke** [comment]
Okay, thanks @topolik :)  Let me know if there is anything I can do.

**Comment by topolik** [comment]
Closing, fixed by https://issues.liferay.com/browse/LPS-63019

**Pull request closed without merging**
