### PR TITLE
LPS-55931

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-55931 Changes based on our Yesterdays discussion

### CODE REVIEW

**Comment by mikakoivisto** [comment]
Added fix for the null pointer

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27630. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
