### PR TITLE
Lps 79347 new2

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/arthurchan35/liferay-portal/pull/28

View just my changes: https://github.com/topolik/liferay-portal/compare/arthurchan35:d460135571...46d29964be
View total diff: https://github.com/topolik/liferay-portal/compare/719c8f5fca...46d29964be

**Pull request closed without merging**
