### PR TITLE
LPS-61850 Google Login module

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
As discussed this PR only migrates the Google Login plugin from liferay-plugins into a module. It is fully functional so long as you don't try to associate an incomplete user.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by topolik** [comment]
View just my changes: https://github.com/topolik/liferay-portal/compare/stian-sigvartsen:4c28f13efb...b8c676419e

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/34234

**Pull request closed without merging**
