### PR TITLE
LPS-73526 Implement new property to enable enforced timeout for tunnel connections

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by topolik** [comment]
Hi @Alec-Shay, 

you didn't provide the default value. This won't fix the problem, only offers the workaround. 

Maybe we should set the defaults for when portal hits this issue it keeps responsive?

**Comment by Alec-Shay** [comment]
Hello @topolik,

Yes, as is, it only offers a way for users to address it themselves. I didn't put a default value in just because I have no idea what that should be and don't want to make assumptions that can change behavior expected for users. If you think we should add a default, what do you think it should be?

**Comment by topolik** [comment]
I see. But clients can already set `sun.net.client.defaultConnectTimeout` system property to workaround this problem. It's the same workaround.

So if we want to provide any different solution then it means to set the timeout to some value.

I would vote for 30 seconds. This won't break existing environments and will keep portal UI at least a bit responsive.

Also we should document this property.

And add some error handling when timeout happens and mention the property in the log message. We still might break some existing environments.

Can you please resend? Thanks.

**Comment by Alec-Shay** [comment]
@topolik We actually suggested they set this property, but this was rejected because they posit that there should be a way to specifically set it for tunnel connections in Liferay (and we tend to agree in support). We think just having the means to do so would probably suffice for them, although setting a default may be preferable.

I'll work on the logging and add a default value. When you say we should document this property, where are you referring to exactly?

**Comment by topolik** [comment]
Well, they are right about specific settings for TunnelUtil but this can happen everywhere in the portal. For us to fix just one place is like ignoring this problem.

I found 55 times `openConnection()` but only 3 times `setConnectionTimeout`

Is it possible for you to find & fix all these places + create a portal property (filtered?) for each case so that we can control each place? 

RE documentation - probably some staging FAQ. Please ask @matethurzo or @sez11a

Thank you!

**Comment by Alec-Shay** [comment]
@topolik So, just to be clear -- you want me to find roughly 55 uses of openConnection() and test and implement a similar solution for each one, and add more error handling, logging, and documentation for each? I think it may be possible but with testing it may take a really long time. What is a filtered portal property, by the way? Or do you mean possibly many properties?

As I'm trying to get a fix through for a client, I think that may need to be delegated a bit differently for time concerns. Could we in the meantime move forward with this fix in particular? Once I've added the logging of course.

**Comment by Alec-Shay** [comment]
Re-sent at: https://github.com/topolik/liferay-portal/pull/454

**Pull request closed without merging**
