### PR TITLE
LPS-54084

### PR DESCRIPTION
**Pull request by dustinryerson**
@Preston-Crary

### CODE REVIEW

**Comment by dustinryerson** [comment]
Dependent plugins fix: https://github.com/topolik/liferay-plugins/pull/4

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @Preston-Crary, I got a conflict while rebasing on master. Can you please rebase and resend? Thank you!

**Comment by Preston-Crary** [comment]
Based and resent https://github.com/topolik/liferay-portal/pull/134

**Pull request closed without merging**
