### PR TITLE
LPS-55706 Reset failed login counts on successful login

### PR DESCRIPTION
**Pull request by laszlocsontos**

### CODE REVIEW

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @vilmospapp,

I don't see the change in authenticateForJAAS, you decided to skip JAAS?

**Comment by vilmospapp** [comment]
Hi Tomas,

I decided to handle it on a sepatate ticket to avoid too complex setup and  test procedure for QA. Furthermore I didn't want to grab JAAS for an initially WebDAV issue.

**Comment by topolik** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26753. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
