### PR TITLE
[TS] LPS-87050

### PR DESCRIPTION
**Pull request by jonathanmccann**
Here are the changes as discussed. I wasn't sure what you meant by inconsistencies of hiding the back URL. The only thing I could think of is doing something like the following:

```
<liferay-ui:header
	backURL="<%= redirect %>"
	title='<%= (gadget != null) ? gadget.getName() : "new-gadget" %>'
	showBackURL="<%= gadget %>"
/>
```

If you want that I can push up another commit. If you had something else in mind let me know and I can do that as well.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
https://github.com/topolik/liferay-portal-ee/pull/178 depends on this pull.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Pushed an update to avoid an NPE with the `_backURL`.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/65080
View total diff: https://github.com/topolik/liferay-portal/compare/7263a2c888...c94cf549df

**Comment by topolik** [comment]
I tested the gadget and it's fine as it is. Thanks @jonathanmccann

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/65083
View total diff: https://github.com/topolik/liferay-portal/compare/4a90689321...fc567ca414

**Pull request closed without merging**
