### PR TITLE
[TECHNICAL-SUPPORT] LPS-75184

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by topolik** [comment]
Hi guys, thanks for the fix but the issue is wrong from the very beginning.

The problem with this fix (and the whole thinking) is that when customer disables `portlet.add.default.resource.check.enabled` then all portlets can be accessible. This is a huge security hole!

When the check is disabled we simply cannot allow to display every portlet.

The correct fix of this whole story is to either:
1, Place the portlet on the page. Right now it's not on the page and is invoked dynamically
2, If they want to invoke the portlet dynamically, then they must specify `add-default-resource` inside `portlet.xml` init params and set it to true.

The problem is in DB inconsistency. I need to connect with the support.

**Comment by ChrisKian** [comment]
Hi @topolik,

Does this also apply if the portlet is added to the property "portlet.add.default.resource.check.whitelist"?  Shouldn't portlets in this list bypass any and all security checks?

Thanks!

**Comment by topolik** [comment]
Hi @ChrisKian,

the short answer is no.

Here is a long one to answer your questions about how it's designed.

Usually portlets can be displayed only when they are placed on a page. Said the other way around, they cannot be displayed if they are not placed on the page.

But sometimes we need to display portlets dynamically. For example "edit article"  link from Web Content Display portlet that opens journal admin portlet that is usually not on the page. So to allow some portlets to be displayed dynamically we added the `add-default-resource` feature. The name comes from historical implementation where we added default resource permissions during portlet display so that we could check permissions

But to avoid displaying such portlets by anybody and anywhere just by guessing the URL we added `p_p_auth` token check. This ensures that only users with possession of the token can access the portlet. Users usually get the token inside some "privileged" action link, like the "edit article" example.

The thing is that every security check should have a way to be disabled or whitelisted. Here we go with  `portlet.add.default.resource.check.enabled` and `portlet.add.default.resource.check.whitelist`.

Now it should be clear that both properties influence how the `add-default-resource` security check behaves. 

When portlet is not `add-default-resource` enabled, then those properties don't apply.

**Comment by ChrisKian** [comment]
Thank you for the detailed answer @topolik!

**Pull request closed without merging**
