### PR TITLE
Lps 79347 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
@topolik 
This PR is an update to what I have worked on.
I think it's more appropriate to backgroudtask in this case, as it provides a mechanism to retrieve status of the background task(, which can be used for displaying process infomation, I believe).

I am trying to add progress bar to the UI, but 
I have a question if you can answer:
Since I added the button in server admin page(resources.jsp), I created the backgroundTaskExecutor class in server-admin-web module, but I am not sure such class should be here in this module. Also I noticed reindex has been moved out of server-admin and has its own search-admin module now.
From what I have seen, none of actions in server-admin page will show a progress bar, but the actions in search-admin has. And I think the search-admin has more control of its jsp page than server-admin, that's probably why search-admin can have progress bar.
Is it a better idea to have seperate module?

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@topolik 
Added a commit as what you suggested.

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Pull request closed without merging**
