### PR TITLE
LPS-60139 ii

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
I was able to keep a lot of the old code from the FacebookConnectAction Struts action, this is now in FacebookConnectRedirectURIServlet.

Following our conversation about how to best integrate error keys from modules into the login portlet, I decided to go with adding a dynamic-include point as you suggested (instead of MVCRenderCommand). I think It is probably a useful extension point for other reasons, like enabling portals to show informative content to their users when logging in.

Happy to discuss / change anything :)

FYI - Once merged, we only need to tweak /navigation/facebook.jsp in order to support Facebook login without a popup. But I'll raise a separate issue for that

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by topolik** [comment]
Hi Stian,

this pull is too big. We need to create subtasks and send parts of it. For example 041029ac2a707ce23ebce9048cedf45b85e072a0 is so big that it would deserve own PR.

On the other hand, these 2 commits can be just one: c3229abcbc7cfc4ca9225cd2b9b0f5340b45b2c9 db4286dff7201fa25718205fdce68f61279e1270

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/stian-sigvartsen/liferay-portal/pull/11

View just my changes: https://github.com/topolik/liferay-portal/compare/stian-sigvartsen:513c724bb6...d8aa6d45dd
View total diff: https://github.com/topolik/liferay-portal/compare/029fba875b...d8aa6d45dd

**Pull request closed without merging**
