### PR TITLE
[TECHNICAL-SUPPORT] LPS-58167 JAAS login doesn't work: alternater solution

### PR DESCRIPTION
**Pull request by lipusz**
Hi Tomas,

What do you think about this version?

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
Rebased.

Hi Tomas,

I kindly ask you to have a look at this as soon as possible, as the related customer issue has been pending for a while and soon we will need to update them and I don't want to release anything as an SDH since it's not an easy-fix, it may cause unforeseen regressions if don't spend time enough to think it through.

Thanks in advance,
Tibor

@topolik

**Comment by topolik** [comment]
Hi Tibor,

at first I thought it could work, it is a nice idea. But I'm sorry now I see where it fails.

The problem is that existing code expects request.getRemoteUser() to return userId. But in the case when JAAS is enabled it can return screenName/email. Nothing in portal (except PortalImpl) is prepared for it.

We could fix portal, but the same situation is with customer portlets. If they rely on getRemoteUser() to return authenticated user ID then their portlets stop to work :( They would need to reimplement them and use JAASHelper (which is in portal-impl).

I'm trying to find a fix...

**Comment by lipusz** [comment]
Hi Tomáš,

I'm pretty sad. 😑 I really don't have more ideas how to fix it gracefully,
it's... like a porcelain.

I trust you, you're my last hope. Thanks for looking into this! Feel free
to reach me over Skype any time.

Regards,
Tibor

@topolik

On Thu, Sep 10, 2015 at 4:45 PM, Tomáš Polešovský <notifications@github.com>
wrote:

> Hi Tibor,
>
> at first I thought it could work, it is a nice idea. But I'm sorry now I
> see where it fails.
>
> The problem is that existing code expects request.getRemoteUser() to
> return userId. But in the case when JAAS is enabled it can return
> screenName/email. Nothing in portal (except PortalImpl) is prepared for it.
>
> We could fix portal, but the same situation is with customer portlets. If
> they rely on getRemoteUser() to return authenticated user ID then their
> portlets stop to work :( They would need to reimplement them and use
> JAASHelper (which is in portal-impl).
>
> I'm trying to find a fix...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topolik/liferay-portal/pull/190#issuecomment-139268608>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer

Team Lead, Platform TS, EMEA
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by topolik** [comment]
Hi Tibor,

FYI: I asked also @mikakoivisto to bring some new light! :)

Thanks.

**Comment by mikakoivisto** [comment]
I think you guys were really close to the solution. The problem we have is that MainServlet is trying to do the same things as SecureFilter but SecureFilter is always ran before MainServlet so what ever MainServlet does messes up things. So my solution is to wipe out all duplicate logic from MainServlet and let SecureFilter handle it. Also I've fixed PortalImpl.getUser() so that it uses JAASHelper to get the userId. We should be only running into this block of code when user is logging in and SecureFilter hasn't wrapped the request yet. 
I can send Tomas my changes and QA has to test this very thoroughly on all AppServers to make sure we didn't break anything.

**Comment by mikakoivisto** [comment]
My suggested solution for the issue https://github.com/topolik/liferay-portal/pull/192

**Pull request closed without merging**
