### PR TITLE
LPS-56015

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Preston-Crary

### CODE REVIEW

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @Preston-Crary 

does this mean that every HTML form can be submitted with p_auth token inside the HTTP request body - from inside <form> ?

If so, can we attach onSubmit event on every HTML POST form and move the token inside the form?

**Comment by Preston-Crary** [comment]
Yes, every html form can now have the p_auth token inside the request body.

Sorry, my JavaScript abilities are still not quite where I want them to be.  Moving the token inside the form is what 64e4dc8f4dd25aa526711ec8101097439472fcf2 should be doing.  Let me know if there's a better way / place to do this.

**Comment by topolik** [comment]
I think your JS is fine.

My idea is to process whole DOM, find all HTML forms with method=POST - not only <aui:form> - and if we find p_auth parameter in the form action, move it into form hidden input. This way we would eliminate also issues in custom portlets.

I think we could do it after page loads, but sometimes we use JS to submit forms. We would need to discuss deeper these cases.

What do you think?

Thanks.

**Comment by Preston-Crary** [comment]
I think it would be optimal to make sure custom portlet forms are covered even when not using AUI.  However, that would be very difficult to do. Can we pursue custom non-aui forms on a separate ticket?

From a support perspective doing it this way is clearer because when clients have concerns about security in their custom plugins we can simply direct them to either use aui:form rather than having some JS running in the background that may or may not be able to cover their use case.

One of the reasons we needed to move the logic from the form/start.jsp into util.js is because we often add the action URL after the form is created. Running on load wouldn't work in these cases either.

Another case to consider is if a developer decides to make a fancy UI using JS to hide / reveal a form, we wouldn't be able to catch that the first time the page loads.  We would need to constantly run in the background searching every time any change was made to the DOM which could cause performance issues.

**Comment by Preston-Crary** [comment]
@topolik 
We may also want this to go through the performance team to double check if it causes any regressions. I'm fairly sure 8893f4293419bffedac1d63c703b3d829e7e288a won't cause any problems but I want to make extra sure because we do this even when the user isn't authenticated.

Do you have any other questions / concerns about this pull?

**Comment by topolik** [comment]
Hi @Preston-Crary,

I'm fine with it.  Yes please, send it to performance team.

One last thing - if users disable the filter, will portal work consistently?
```
    # The upload servlet request filter is needed to wrap multipart requests
    # into UploadServletRequest. It should not be disabled because it is needed
    # by many Liferay portlets and helps protect against CSRF attacks.
    #
    com.liferay.portal.servlet.filters.uploadservletrequest.UploadServletRequestFilter=true
```

Thanks.

**Comment by Preston-Crary** [comment]
No it won't work consistently, anything relying on the upload servlet request won't actually get one.  That's why the property says to never disable the filter, the other filters that should not be disabled document this in the same way.

**Pull request closed without merging**
