### PR TITLE
[TECHNICAL-SUPPORT] LPS-58167 JAAS login doesn't work when LiberalScreenNameValidator enabled and user's screenName contains digits only

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-58167

Hi Tomáš,

This is the fix for the issue we were discussing over Skype last week. I've tested the solution, and the necessary pre-and post-login events were executed and threadlocals were also populated correctly.

Quick summary of the technical background: https://issues.liferay.com/browse/LPS-58167?focusedCommentId=658167&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-658167

Let me know if you have any concerns, I'm open for starting a discussion about it, but I could not find a better way to fix it.

Thx,
Tibi

### CODE REVIEW

**Comment by lipusz** [comment]
Hi,

Did you have time to review this pull?

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi @topolik 

Please, review it today as it's getting urgent for the subscriber.

Thanks,
Tibor

**Comment by lipusz** [comment]
waiting

@topolik :-)

**Comment by topolik** [comment]
haha :)

But I see you're still improving your commit :)

Anyways, I think this could work.

But please fix also these:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/UserResolver.java#L38

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/webdav/WebDAVServlet.java#L96

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/webdav/WebDAVRequestImpl.java#L64

Thank you.

**Comment by lipusz** [comment]
Sure! Will update the branch shortly.

p.s.: bu who is Will? ^^

On Fri, Sep 4, 2015 at 11:55 AM, Tomáš Polešovský <notifications@github.com>
wrote:

> haha :)
>
> But I see you're still improving your commit :)
>
> Anyways, I think this could work.
>
> But please fix also these:
>
> https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/UserResolver.java#L38
>
>
> https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/webdav/WebDAVServlet.java#L96
>
>
> https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/webdav/WebDAVRequestImpl.java#L64
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topolik/liferay-portal/pull/188#issuecomment-137693493>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by topolik** [comment]
OK, we need to test that. 

SecureFilter and AuthVerifierFilter sets the remoteUser to be userId (into ProtectedServletRequest) so there can be valid userId inside remoteUser but those 3 classes above wont' recognize it now!

**Comment by lipusz** [comment]
But we cannot rely on JAASHelperUtil.getUserId either at these places, as if we resolve the userId too early we may break other parts (e.g. MainServlet.loginUser) that expect to get a JAAS remoteUser (so e.g. a screenName) not a userId.

I'm not sure which parts I should modify then :-/

**Comment by topolik** [comment]
Tibor, I've thought about it and I think we could fix simply SecureFilter, if that's the component where it fails first.

If JAAS is enabled, change the logic to adapt to screenName in remoteUser and don't call Portal.getUser(). After then create the protected servlet with userId as it is now.

What do you think, would it work?

**Comment by lipusz** [comment]
Hi @topolik ,

>But I see you're still improving your commit :)

It's because I have rebased the branch to latest master every day.

> f JAAS is enabled, change the logic to adapt to screenName in remoteUser and don't call Portal.getUser(). After then create the protected servlet with userId as it is now.

I'm looking into it, though I can see a difference in what we set in the ProtectedSR:

in Secureífilter, we don't set the 'userId' attribute, but the the 'user':

````java
	protected HttpServletRequest setCredentials(
			HttpServletRequest request, HttpSession session, long userId,
			String authType)
		throws Exception {

		User user = UserLocalServiceUtil.getUser(userId);

		String userIdString = String.valueOf(userId);

		request = new ProtectedServletRequest(request, userIdString, authType);

		session.setAttribute(WebKeys.USER, user);
		session.setAttribute(_AUTHENTICATED_USER, userIdString);

		initThreadLocals(request);

		return request;
````

while in the MainServlet.loginUser, we do

````java
// ....
		HttpSession session = request.getSession();

		session.setAttribute(WebKeys.USER, user);
		session.setAttribute(WebKeys.USER_ID, Long.valueOf(userId));
		session.setAttribute(Globals.LOCALE_KEY, user.getLocale());

// ...
	}
````

**Comment by lipusz** [comment]
I think, it would be faster to discuss it via Skype. Ping me when you have time.

**Comment by lipusz** [comment]
Hi @topolik 

The changes we agreed in to add to SecureFilter
````java
			User user = null;

			if (PropsValues.PORTAL_JAAS_ENABLE) {
				String remoteUser = request.getRemoteUser();

				if (remoteUser != null) {
					long userId = JAASHelper.getJaasUserId(
						PortalUtil.getCompanyId(request), remoteUser);

					user = UserLocalServiceUtil.getUser(userId);
				}
			}
			else {
			 user = PortalUtil.getUser(request);

			}

			if (user == null) {
				user = PortalUtil.initUser(request);
			}

			initThreadLocals(user);
````

generates a NoSuchUserEx in the MainServlet, since its "loginUser" method also resolves the remoteUser:

````java
	protected long loginUser(
			HttpServletRequest request, HttpServletResponse response,
			long companyId, long userId, String remoteUser)
		throws PortalException {

		if ((userId > 0) || (remoteUser == null)) {
			return userId;
		}

		if (PropsValues.PORTAL_JAAS_ENABLE) {
			userId = JAASHelper.getJaasUserId(companyId, remoteUser);
		}
		else {
			userId = GetterUtil.getLong(remoteUser);
		}

		EventsProcessorUtil.process(
			PropsKeys.LOGIN_EVENTS_PRE, PropsValues.LOGIN_EVENTS_PRE, request,
			response);

		User user = UserLocalServiceUtil.getUserById(userId);
````

but the request is already a wrapped PSR and the remoteUser is the userId.

**Comment by lipusz** [comment]
I think, we cannot remove the JAAS logic from the MainServlet, since SecureFilter can be disabled, so it has to be prepared to handle JAAS.

I was wondering, if I could preserve the original remoteUser from the standard request (userId, screenName, emailAddress) when JAAS enabled in the ProtectedSR, so MainServlet would not fail.

**Comment by lipusz** [comment]
Please, see: https://github.com/topolik/liferay-portal/pull/190

**Comment by lipusz** [comment]
https://github.com/topolik/liferay-portal/pull/192

**Pull request closed without merging**
