### PR TITLE
LPS-83129 Let the sanitizer allow the "type" tag for ordered lists

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @topolik 

Could you please check this pull request?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Hi @topolik 

I am wondering if you could find time to take a look at this pull request.
Please let me know if you need any further help or explanation on the issue and the solution.

Thank you and best regards,
István

**Comment by topolik** [comment]
Hi Istvan,

I had to make some corrections. Please see the PR to Brian.

Thanks.

**Comment by IstvanD** [comment]
Many thanks @topolik for forwarding it!

**Pull request closed without merging**
