### PR TITLE
[TECHNICAL SUPPORT] LPS-62165 Login redirect loop and Http 414 when server uses proy.path and when Guest user tries to login and has no permission on the default landing page of the site

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-62165

Hi,

Could you please take a look at this?
Or forward to an other team if you want, as I really don't know where to send this :)

Br,
Norbert

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Tomas,

Can you please push it forward if you agree with Ádám's changes?

Thx,
Tibi

@topolik

**Comment by topolik** [comment]
Hi guys, how were you able to test it on master? I got several 404 for 108 CSS/JS resources and cannot sign in. The proxy is not working in master at all?!

**Comment by NorbertKocsis** [comment]
On master you have to create the pages without the proxy settings. The issue itself can be tested afterwards.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/35393

View just my changes: https://github.com/topolik/liferay-portal/compare/NorbertKocsis:76c2d77073...8d8bf1a901
View total diff: https://github.com/topolik/liferay-portal/compare/ce5e40fc52...8d8bf1a901

**Pull request closed without merging**
