### PR TITLE
LPS-54042

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-54042 UI for creating Service Access Profiles. Please pay attention to the permissions that they are as you envisioned. If it looks OK to you we can then send it to Nate for UI review

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey Mika,

Can you send some screenshots to Juan Hidalgo and myself for a UX review?
Please describe briefly as well the use cases that this application is intended to cover.

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Pull request submitted to https://github.com/mikakoivisto/liferay-portal/pull/64. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
