### PR TITLE
LPS-95357 Export new package

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by topolik** [comment]
@csierra I believe Brian meant to move it to portal-kernel to the other common functionalities around UpgradeSteps ... https://github.com/brianchandotcom/liferay-portal/pull/72823#issuecomment-491030864

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/73110
View total diff: https://github.com/topolik/liferay-portal/compare/b203820d01...725563d271

**Pull request closed without merging**
