### PR TITLE
[TS] LPS-91722

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-91722](https://issues.liferay.com/browse/LPS-91722)

Hi Tomas,

As per the [request of Tibor](https://github.com/lipusz/liferay-portal/pull/251#issuecomment-471472922), I am sending this directly to you.

Please, feel free to contact me any time if I can help you.

Thank you!
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/69272

View just my changes: https://github.com/topolik/liferay-portal/compare/istvansajtos:4ae7550ab6...2ed0cf9154
View total diff: https://github.com/topolik/liferay-portal/compare/6c18ae4451...2ed0cf9154

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/69273

View just my changes: https://github.com/topolik/liferay-portal/compare/istvansajtos:4ae7550ab6...690f25528d
View total diff: https://github.com/topolik/liferay-portal/compare/6c18ae4451...690f25528d

**Pull request closed without merging**
