### PR TITLE
[TECHNICAL-SUPPORT] LPS-85179

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by topolik** [comment]
ci:test:relevant

**Comment by topolik** [comment]
ci:test:sf

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/jonathanmccann/liferay-portal/pull/1682

View just my changes: https://github.com/topolik/liferay-portal/compare/jonathanmccann:fb6a4fbcdd...7a901b6ab4
View total diff: https://github.com/topolik/liferay-portal/compare/4b502f8f66...7a901b6ab4

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/jonathanmccann/liferay-portal/pull/1684

View just my changes: https://github.com/topolik/liferay-portal/compare/jonathanmccann:fb6a4fbcdd...f994045689
View total diff: https://github.com/topolik/liferay-portal/compare/4b502f8f66...f994045689

**Pull request closed without merging**
