### PR TITLE
[Prioritize] LPS-96877 No need to check restricted classes for unrestricted templates in FreeMarker and Velocity

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-96877

Hey Tomas,

If you agree with the approach, I think we should send it to the Core Infra team too to double-check.

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
I'm updating the test...

**Comment by lipusz** [comment]
Hey Tomas, @topolik 

I'll update the test if the approach is good.

**Comment by lipusz** [comment]
Hi Tomas,

The plan is (if the approach is good) that we are going to include this fix in the security release only for 6.2, because for 7.1 and 7.0 LPS-83801 was already included in a fix pack and we haven't received regressions so far, thus, I'd like to avoid rebuilding 7.1 FP12 and 7.0 FP82 just to include this fix which would delay the release again with at least 1 week.

The release is scheduled to next Tuesday, so we will need a new portal-170 (for 6.2) build by CNQA's monday so that they can test, and i can send the partner bulletin on monday evening PDT.

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/tinatian/liferay-portal/pull/1415

View just my changes: https://github.com/topolik/liferay-portal/compare/lipusz:445ec99edb...c491e41f1a
View total diff: https://github.com/topolik/liferay-portal/compare/21a961b395...c491e41f1a

**Pull request closed without merging**
