### PR TITLE
LPS-96009 Prevent adding non-instanceable portlet to the same page more than once

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@topolik For other issues mentioned in ticket there are separate tickets opened.

**Comment by pavel-savinov** [comment]
Subtasks pull requests:
https://github.com/topolik/liferay-portal/pull/769
https://github.com/topolik/liferay-portal/pull/770
https://github.com/topolik/liferay-portal/pull/771
https://github.com/topolik/liferay-portal/pull/772

**Comment by topolik** [comment]
Thanks Pavel, I move this PR into a subticket too to prevent closing the parent when Brian merges it.

**Comment by topolik** [comment]
Please see 
https://github.com/brianchandotcom/liferay-portal/pull/73621
https://github.com/brianchandotcom/liferay-portal/pull/73624
https://github.com/pavel-savinov/liferay-portal/pull/363
Thanks.

**Pull request closed without merging**
