### PR TITLE
[TECHNICAL-SUPPORT] LPS-99587

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SpencerWoo

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi @SpencerWoo,

this is fixing only a small part of the whole problem. They mentioned also other methods to be fixed (_The same logic is applied elsewhere like updatePasswordManually() adduserWorkflow() updateUser() etc._).

Notice it's not always desired to update the digest: https://github.com/liferay/liferay-portal/blob/9d78ab420bd54bcd0a082beecc747e6caedc88d6/modules/apps/portal-security/portal-security-ldap-impl/src/main/java/com/liferay/portal/security/ldap/internal/exportimport/LDAPUserImporterImpl.java#L1679-L1684

This is a problem in general with SSOs where authentication doesn't use password. I'm not sure if this is to be fixed. I discuss with our team. Thanks.

**Comment by SpencerWoo** [comment]
@topolik Thanks
I changed updateUser()? but you're right the other two mentioned are valid

------

I can make a PTR if preferred but my rationale is (1) I would consider this a digest bug and (2) the SSO concern still exists in the current code - a user can auth and SSO can be used/enabled afterwards.

Theoretically the SSO security concern would be handled on the SSO-side but I haven't looked into that implementation.  Thanks for discussing with your team!

**Comment by stian-sigvartsen** [comment]
I think a PTR would be a useful to progress this discussion. One of our priorities is supporting multi factor authentication. So we need to be careful to not allow ways of bypassing that through protocols like digest auth that have no means to meet that challenge. By requiring at least one successful login via portal UI, this issue is worked out.

/cc @SpencerWoo @topolik

**Comment by SpencerWoo** [comment]
@stian-sigvartsen I've created a PTR here https://issues.liferay.com/browse/PTR-1127

**Comment by stian-sigvartsen** [comment]
@topolik The ticket for this pull request has been resolved as won't fix . See discussion on PTR-1127

**Comment by topolik** [comment]
Thank you Stian!

**Pull request closed without merging**
