### PR TITLE
LPS-88293 - Avoid duplicate code in JSONWebServiceClientImplSSLGetTest

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by lipusz** [comment]
Hey @ivicac 

Do you think you could do the same we're doing in https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/HttpImpl.java#L143-L152?

**Comment by lipusz** [comment]
This way you'd not need to bother with the actual system properties, split etc.

**Comment by topolik** [comment]
Hi @ivicac, looks fine, do you want me to send it to BChan?

**Comment by ivicac** [comment]
Hey @topolik ,
yes ,just push it to Brian.

Hey @lipusz ,
yes, we are doing the same way as Liferay, but as we support custom keystores, too, we have to get system properties manually for that case.

Best Regards

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/67263

View just my changes: https://github.com/topolik/liferay-portal/compare/ivicac:ccc8bd1cd1...9ef870bbc0
View total diff: https://github.com/topolik/liferay-portal/compare/50296f0c44...9ef870bbc0

**Pull request closed without merging**
