### PR TITLE
LPS-87707 [TS] Generate tests to check invalid nonce and nonce is used only once.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,
 taking into account your considerations about the need to use the nonce, by definition, only once I thought about saving the nonce information in the session, so that:

- If customer has shared session the nonce will be shared in all nodes.
- If customer has sticky session the same node will answer same session requests.
- If they don't have any of the previous ones they are facing the same issue since when nonce is validated we save USER in the session.

Kind regards.

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,
 did you have chance to take a look to this new version?
Kind regards.

**Comment by topolik** [comment]
Hi @marianoalvarosaiz, sorry, somehow slipped through.

I'm afraid of using the session. The HTTP Digest Auth spec doesn't specify the use of session cookies so I'm not sure this will work across all clients. Did you try it for example with curl?

Thanks.

**Comment by topolik** [comment]
Hi @marianoalvarosaiz,

I tried the solution and works with chrome/firefox but doesn't work with curl and HttpClient. So there won't be problems with webdav but with API clients. They simply don't reuse cookies while inside the authentication process:

HttpClient (4.5):
```
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.protocol.HttpClientContext;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;

public class Test {
	public static void main(String[] args) throws Exception {
		System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.SimpleLog");
		System.setProperty("org.apache.commons.logging.simplelog.showdatetime", "true");
		System.setProperty("org.apache.commons.logging.simplelog.log.org.apache.http.wire", "DEBUG");

		HttpGet httpGet = new HttpGet("http://localhost:8080/api/jsonws/user/get-current-user");

		CredentialsProvider credsProvider = new BasicCredentialsProvider();
		credsProvider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials("test@liferay.com", "test"));

		HttpClientContext context = HttpClientContext.create();
		context.setCredentialsProvider(credsProvider);

		CloseableHttpClient httpClient = HttpClients.createDefault();
		CloseableHttpResponse response = httpClient.execute(httpGet, context);
		response.close();
	}
}

2019/01/17 11:54:01:431 CET [DEBUG] wire - http-outgoing-0 >> "GET /api/jsonws/user/get-current-user HTTP/1.1[\r][\n]"
2019/01/17 11:54:01:434 CET [DEBUG] wire - http-outgoing-0 >> "Host: localhost:8080[\r][\n]"
2019/01/17 11:54:01:434 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2019/01/17 11:54:01:434 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.6 (Java/1.8.0_191)[\r][\n]"
2019/01/17 11:54:01:434 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2019/01/17 11:54:01:434 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2019/01/17 11:54:01:435 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 401 [\r][\n]"
2019/01/17 11:54:01:435 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2019/01/17 11:54:01:435 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
2019/01/17 11:54:01:436 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1[\r][\n]"
2019/01/17 11:54:01:436 CET [DEBUG] wire - http-outgoing-0 << "Set-Cookie: JSESSIONID=EDE25E943075B4245A8F1A8D0EC53CF6; Path=/; HttpOnly[\r][\n]"
2019/01/17 11:54:01:436 CET [DEBUG] wire - http-outgoing-0 << "WWW-Authenticate: Digest realm="PortalRealm", nonce="ad345452e867c94d0db04cb4819abe0a"[\r][\n]"
2019/01/17 11:54:01:436 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2019/01/17 11:54:01:436 CET [DEBUG] wire - http-outgoing-0 << "Date: Thu, 17 Jan 2019 10:54:01 GMT[\r][\n]"
2019/01/17 11:54:01:436 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2019/01/17 11:54:01:447 CET [DEBUG] wire - http-outgoing-0 >> "GET /api/jsonws/user/get-current-user HTTP/1.1[\r][\n]"
2019/01/17 11:54:01:447 CET [DEBUG] wire - http-outgoing-0 >> "Host: localhost:8080[\r][\n]"
2019/01/17 11:54:01:447 CET [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2019/01/17 11:54:01:447 CET [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.6 (Java/1.8.0_191)[\r][\n]"
2019/01/17 11:54:01:447 CET [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2019/01/17 11:54:01:447 CET [DEBUG] wire - http-outgoing-0 >> "Authorization: Digest username="test@liferay.com", realm="PortalRealm", nonce="ad345452e867c94d0db04cb4819abe0a", uri="/api/jsonws/user/get-current-user", response="384fa5be4aa89bf29ea27ee18a89415f", algorithm=MD5[\r][\n]"
2019/01/17 11:54:01:447 CET [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2019/01/17 11:54:01:448 CET [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 401 [\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "X-XSS-Protection: 1[\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "Set-Cookie: JSESSIONID=A70F8253A372DE47936DC96103AA422A; Path=/; HttpOnly[\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "WWW-Authenticate: Digest realm="PortalRealm", nonce="61f2fe6c0fc5249de9a2677640a0dbb5"[\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "Date: Thu, 17 Jan 2019 10:54:01 GMT[\r][\n]"
2019/01/17 11:54:01:449 CET [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
```

CURL:
```
curl -v localhost:8080/api/jsonws/user/get-current-user --digest -u test@liferay.com:test
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Digest with user 'test@liferay.com'
> GET /api/jsonws/user/get-current-user HTTP/1.1
> User-Agent: curl/7.37.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 401 
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1
< Set-Cookie: JSESSIONID=EF148149B9CBDB3A3657BD48883E41FA; Path=/; HttpOnly
< WWW-Authenticate: Digest realm="PortalRealm", nonce="a1a1505fffc5cd55f7083d3750fbaea0"
< Content-Length: 0
< Date: Thu, 17 Jan 2019 10:28:58 GMT
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'HTTP://localhost:8080/api/jsonws/user/get-current-user'
* Found bundle for host localhost: 0x231b1b0
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Digest with user 'test@liferay.com'
> GET /api/jsonws/user/get-current-user HTTP/1.1
> Authorization: Digest username="test@liferay.com", realm="PortalRealm", nonce="a1a1505fffc5cd55f7083d3750fbaea0", uri="/api/jsonws/user/get-current-user", response="8f82fe4e9612dbabcde44148e917c37f"
> User-Agent: curl/7.37.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 401 
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1
< Set-Cookie: JSESSIONID=1A746DEB91E56EC89FA2E27FE3C0F6DE; Path=/; HttpOnly
* Authentication problem. Ignoring this.
< WWW-Authenticate: Digest realm="PortalRealm", nonce="6709996acbbe6aaf7884c6a64caebd76"
< Content-Length: 0
< Date: Thu, 17 Jan 2019 10:28:58 GMT
< 
* Connection #0 to host localhost left intact
```

**Comment by topolik** [comment]
Can you please resend the one distributing nonces through the clustered portal cache? We just need to remove them from the cache once used, another option would be to update some attribute of the nonce to signal it was already used.
Thanks.

**Comment by marianoalvarosaiz** [comment]
Thanks for your suggestion, see https://github.com/topolik/liferay-portal/pull/694

**Pull request closed without merging**
