### PR TITLE
LPS 59181

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
After rebasing to the latest master, the language keys issue appears to be resolved. Thanks!
There is an outstanding issue, the dynamic-include OpenID login option isn't picking up the language keys. I have tried to publish the keys to PortletKeys.LOGIN & PortletKeys.FAST_LOGIN as well, but then the portal doesn't even start (numerous stacktraces)!

Once @philipjones03 has got a common bundle working with NTLM, I will send a second PR to integrate that code.

p.s. The OpenID login action doesn't work at present, but I will create a separate issue for that.

### CODE REVIEW

**Comment by topolik** [comment]
Thanks Stian!

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by topolik** [comment]
Thank you, please see https://github.com/stian-sigvartsen/liferay-portal/pull/7.

**Pull request closed without merging**
