### PR TITLE
LPS-54599 Make portlet URL CSRF tokens single use only

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
I didn't change PortletKeys, I don't think this test failure applies to my changes.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @Preston-Crary,

interesting solution!

However, I'm sorry, I see two problems here:
1, you merged p_p_auth token and p_auth token
2, it doesn't work for two browser tabs or AJAX portlet requests

(1) p_p_auth token has another security check. If you replace the token in session during CSRF check the p_p_auth token check will fail.

Please see:
* https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/SecurityPortletContainerWrapper.java#L193-199
* https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/DefaultLayoutTypeAccessPolicyImpl.java#L216-220

Another thing is that developers use AuthTokenUtil.getToken() to get the token in their own code: https://github.com/liferay/liferay-plugins-ee/blob/ee-6.2.x/portlets/osb-lcs-portlet/docroot/members/view.jsp#L146

(2) This cannot work in the case you have 2 browser tabs:
1, Sign in
2, Go to Control Panel > Site > Web Content, click Add Folder
3, Open new tab in browser
4, Go to Control Panel > Site > Web Content, click Add Basic Web Content
5, Publish the web content and close tab
6, In the first browser tab finish creating the new folder, click submit

Expected result: the folder should be created
Actual result: error in logs `[SecurityPortletContainerWrapper:335] Reject process action for http://localhost/group/control_panel/manage on com_liferay_journal_web_portlet_JournalPortlet`

Also, if there is a portlet AJAX call that periodically updates something in portlet, the second and all further requests will fail.

**Comment by Preston-Crary** [comment]
Hi @topolik 
The only way I can think of making single use tokens work with multiple tabs is to create many different tokens in the session - one for each URL that needs a token.  This would mean every time we call AuthTokenUtil.getToken() it would return a new token after adding it to the session.

We would then only invalidate the one we used and many unused tokens would remain in the session.

**Comment by topolik** [comment]
Yeah, there are two verification problems:
1, if the token is correct
2, if the token was used

You are right, a simple solution is to save all emited tokens + all used tokens, which is memory expensive. I believe there is a solution where we move it from the space complexity to use also time complexity to make it more usable.

----

My idea is to have a sequence for generating tokens. This token sequence must have following attributes:
- portal keeps only starting point of the sequence or other secret/key in user session to verify the token comes from this sequence
- user/attacker cannot predict any token from set of known tokens

With such sequence we can keep only the sequence starting point (a pseudo-random seed) or secret key in the session.

If we also keep together with the token it's order in the sequence (1,2,3,...) we can use BitSet class to mark already used tokens.

*Implementation part - e.g. using HMAC:*
- let's have the sequence to be really the ordinal numbers, i.e.1,2,3,4,5... :)
- let's use HMAC to generate the token and a cryptographically strong random key saved in session
- the token would have this syntax "`sequenceNum`-`base64(HMAC(sequenceNum, sessionKey))`", for example: `1-FO3Pov57HQOKmdtSEm03tHVxX9A`
- for verification, we would look at the sequence number and check our BitSet to make sure it wasn't used yet
- then we would generate HMAC and compare it with the received HMAC to make sure it's valid
- then we would update BitSet with the used sequence number

What we need to store in session:
1, HMAC key - byte[]
2, sequence number - probably atomic integer
3, BitSet .. probably some ours memory-friendly thread-safe implementation

What we need to compute:
1, HMAC for generating token (once per response)
2, HMAC for comparing token (once per action request)

----

The above can be the output of AuthTokenUtil.getToken() that is used from Java code.

And we need something similar for JavaScript to be able to perform multiple AJAX calls => we need to change Liferay.authToken from a property to function in top_js.jspf. This function would generate the tokens very similary, we would only need to define the key and starting sequence number. The verification on the server would be similar, however for the AJAX calls we should have another sequence and BitSet and perhaps also the key.

**Pull request closed without merging**
