### PR TITLE
[TECHNICAL-SUPPORT] LPS-67209

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Preston-Crary

### CODE REVIEW

**Comment by rotty3000** [comment]
While most of this change looks fine, I question whether the caches should be cleared in a model listener which is not transactionally safe. What would be better is to only clear the cache as the result of the successful transaction. The model listener could push a transaction callback though.. that would be fine. That would at least separate the logic of adding the callback nicely away from the service impl.

**Comment by Preston-Crary** [comment]
Not sure why clearing the cache needs to be aware of the transaction.  Worst case is pretty rare (transaction is rolled back) and only results in having to refetch entries in the cache from the database.  Is there something I'm missing?

**Comment by rotty3000** [comment]
Flushing entire caches is SUPER expensive.

We should take every precaution to only do it when absolutely necessary.
However, I would defer to what @shuyangzhou recommends here... but my gut
says that we should stray on the side of being careful.

**Comment by topolik** [comment]
I don't understand the transactional part of this, I'd say it's part of transactions because model listeners are called from persistence that requires transaction for these operations, but I probably miss something.

But the PR consistently breaks `UserBagFactoryTest.testGetGroups` and it would be good to retest it on top of https://github.com/JorgeFerrer/liferay-portal/pull/767, because currently the test ignores usergroup roles (and I'd guess organization roles too) 

Beside, can you please improve the cache invalidation? Before this change the code cleared only the user associations. Now it clears all permissions for all users, making things worse then they were before. But I'm no performance expert /cc @shuyangzhou

Please resend, thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/topolik/liferay-portal/pull/367

**Pull request closed without merging**
