### PR TITLE
LPS-115547 Update exported package version

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:sf

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/topolik/liferay-portal/pull/847

View just my changes: https://github.com/topolik/liferay-portal/compare/csierra:9313148b9f...867218a616
View total diff: https://github.com/topolik/liferay-portal/compare/f833273185...867218a616

**Pull request closed without merging**
