### PR TITLE
OAUTH2-286 Why not remove tracking of bundle?

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Tomas.
Following on from our discussion I've provided a couple of approaches to removing bundle tracking.

I think the tracking provides very little benefit because deployed code is always trusted, so why should we stop the portal admin from replacing bundles and re-mapping old authorizations?

It might have made more sense in the past when we created ScopeGrant records when handling the authorization request decision. Kind of "lock" the decision in, but see my earlier comment.

1) Completely remove it: 39b26c6
2) Leave it in LiferayOAuth2Scope (not SemVer change) and use a Supplier to resolve it on demand: 
94250a5

I'm in favor of the second approach because then we maintain a way of resolving the bundle related to ScopeFinders which might be useful in showing JAX-RS endpoints related to scopes etc. in future. Also we avoid the SemVer change.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@topolik I'm only sending you this to get your view on the removal of the bundle tracking in the persistance layer given your experience with this code. Once you've reviewed you can re-assign it back to me and I'll tidy up :)

**Comment by topolik** [comment]
Hi Stian, 

I'm fine if we add new API to simplify the application scope handling but be careful with removing, we need to deprecate.

Related to the bundles, now we allow one more level of abstraction, i.e. an application scope can be exposed/consumed by multiple modules. Previously it was - I granted the scope to be used by this module. Now it would be - I granted the scope to be used by app, but can be used on any bundle. Am I correct?

**Comment by stian-sigvartsen** [comment]
Hi @topolik . I'll take care to deprecate everything that is no longer used.

Yes that's correct. So in essence the app can migrate between modules if desirable. I would see this as a problem if untrusted apps can be deployed. i.e. overriding the JAX-RS application service with one with a higher service ranking. But we're dealing with trusted code.

**Comment by stian-sigvartsen** [comment]
To capture our offline conversation...
We decided that bundle tracking is necessary for when Resources get attached to Applications from other bundles. We decided to go with using @Reference on caller side to ensure ScopeFinders are available.

Also in follow up conversation with @csierra we discussed that bundle tracking is also necessary for future plans to bind scopes to specific Java methods on resources.
We tweaked the previous decided approach, dropping the @Reference approach and instead providing the bundleSymbolicName to the API.

**Comment by stian-sigvartsen** [comment]
Please see csierra/liferay-portal/pull/581

**Pull request closed without merging**
