### PR TITLE
LPS-97073 Instance portlet should not be accessed by generic portlet …

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/75658

View just my changes: https://github.com/topolik/liferay-portal/compare/arthurchan35:b5fa6f4c69...f761e23ea6
View total diff: https://github.com/topolik/liferay-portal/compare/4d96979f86...f761e23ea6

**Pull request closed without merging**
