### PR TITLE
LPS-83431 Google & Facebook SSO doesn't redirect user to home page

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
90a2581 will fix [LPS-84422](https://issues.liferay.com/browse/LPS-84422) as well

**Comment by csierra** [comment]
Sent to frontend infra for review https://github.com/jbalsas/liferay-portal/pull/1413 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
ci:close <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Thanks @csierra !

**Pull request closed without merging**
