### PR TITLE
[TECH-SUPPORT] LPS-55786 Portlet preferences are visible to guest users

### PR DESCRIPTION
**Pull request by laszlocsontos**

### CODE REVIEW

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @istvansajtos,

seems it's working well for "edit" mode, but it's not for the others (edit_guest, about, config, help, ...)

I don't know if we should check any permissions for the other modes beside Portlet.VIEW, but I think at least for edit_guest there should be something.

I'm waiting for @rotty3000 or @JorgeFerrer to see.

Thanks.

**Comment by topolik** [comment]
Hi @istvansajtos,

please can you add portlet-mode specific permission checks and resend?

all modes ... VIEW
+
config ... CONFIGURATION
edit ... PREFERENCES
edit_defaults ... PREFERENCES
guest_edit ... GUEST_PREFERENCES

Thank you.

**Comment by istvansajtos** [comment]
Hi Tomas,

Many thanks for the detailed guidance! I made the modifications according to your request and sent a pull to Laszlo. Hopefully he will forward it to you soon.

Thank you,
Istvan

**Pull request closed without merging**
