### PR TITLE
LPS-68220 OpenAM

### PR DESCRIPTION
**Pull request by martamedio**
Please, see: https://github.com/topolik/liferay-portal/pull/608#discussion_r218420077

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reopen

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/63319
View total diff: https://github.com/topolik/liferay-portal/compare/4436d9d667...9f73a8b465

**Pull request closed without merging**
