### PR TITLE
LPS-55273

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
When xml.security.enabled = false, we do not execute isCallerWhitelisted to avoid CPU consumption.

@topolik there is any trouble adding this check?

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26102. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Closing, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
