### PR TITLE
LPS-111932

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-111932

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Duplicates https://issues.liferay.com/browse/LPS-111235

**Pull request closed without merging**
