### PR TITLE
LPS-60164

### PR DESCRIPTION
**Pull request by mhan810**
Waiting  for https://github.com/brianchandotcom/liferay-portal/pull/31956

### CODE REVIEW

**Comment by mhan810** [comment]
@topolik I made some minor adjustments to packages and etc.  I've kept the dynamicInclude registry name as com.liferay.login.web, but I've made the JSPs and etc login-web to be more inline with the others (e.g. portal-settings, etc)

I've also done some minor repackaging of classes.  I don't think I've broken anything but sending back for some tests.

If all go, please go ahead and send to BC

**Comment by topolik** [comment]
Hi @mhan810,

I decided to keep the JSP directories prefixed with the module FQN.
portal-settings-web is only our development naming, but outside it will be
always com.liferay.portal.settings.web, the same with login-web and
com.liferay.portal.login.web. Because we are hooking into that module I
wanted to make it clear.

But it seems Brian didn't get it :)
https://github.com/brianchandotcom/liferay-portal/pull/31788#issuecomment-153913346

-- tom +

**Comment by mhan810** [comment]
Hehe k I suspected he wouldn't take that for jsps in the resources folder.

**Comment by topolik** [comment]
Mike, you closed the PR, anything wrong?

I'm just before sending it to Brian, rebased on master changes

**Comment by topolik** [comment]
Ok, please see https://github.com/mhan810/liferay-portal/pull/835

**Pull request closed without merging**
