### PR TITLE
[TECHNICAL-SUPPORT] LPS-86161

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @ricky-pan 

Relevant tickets:
https://issues.liferay.com/browse/LPS-86161
https://issues.liferay.com/browse/LPP-31875

Notes from Ricky:

> Issue: StaleObjectStateExceptions currently log the entire object from the database, because it calls the object's `toString()` method. This is an issue because not all parties have the same understanding of safe logging, and this does not allow for an easy way to change what is logged.
> 
> Solution: Serialize an object using Liferay's JSONSerializer, which omits field that are hidden from json-services when building services. Fields that are not available to a user with highest permission when calling JSON Web Services should not be accessible within the logs, so this will standardize how models are printed.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi guys, 

/cc @joshuacords

thanks, I see lot of hard work on this.

Related to the permissions, I think this is not what we want. 

Currently the admin role is checked only here: https://github.com/topolik/liferay-portal/blob/8af330ce4da2fd1a80128a83af653feed0bc47f5/portal-impl/src/com/liferay/portal/json/transformer/CompanyJSONTransformer.java#L35-L40

**This would mean we do show companyKey in logs.**

Another use is here, where we compare userId:
https://github.com/topolik/liferay-portal/blob/8af330ce4da2fd1a80128a83af653feed0bc47f5/portal-impl/src/com/liferay/portal/json/transformer/UserJSONTransformer.java#L40-L45

This would mean we would not leak any passwords except **admin password, this one would be printed into logs**.

----

Thinking about it, the correct solution seems to use either the default user or don't use permission checker at all. The final effect is the same in both cases. So I lean towards removing the permission checker from the code here.

I fix it and send to Brian Chan, please let me know your ideas.

Thanks!

**Comment by topolik** [comment]
Thanks @ricky-pan, you are right.

By an accident I found out we need to improve this even further.

I'm testing the StaleObjectExc by running several times in parallel:
```
while true; do curl http://localhost:8080/api/jsonws/user/get-current-user -u test@liferay.com:test2 >/dev/null 2>&1; done
```

And found out that UserJSONTransformer operates on the original object. If we call it from the persistence layer it happens that the object from Hibernate session is reused later, but it has modified fields by the transformer and those get into DB :(

**Comment by ricky-pan** [comment]
Can we instead transform a copy of the database object from the ExceptionTranslator class?

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/65053

View just my changes: https://github.com/topolik/liferay-portal/compare/SamZiemer:4c80c9adab...684b279715
View total diff: https://github.com/topolik/liferay-portal/compare/33abe875ac...684b279715

**Comment by topolik** [comment]
Yeah, that's the plan :)

**Comment by ricky-pan** [comment]
Thanks @topolik, this looks great. :)

**Pull request closed without merging**
