### PR TITLE
[TS] LPS-86681 PasswordModifiedFilter check is unnecessary during impersonation.

### PR DESCRIPTION
**Pull request by brianikim**
Hello @topolik ,

Resending from https://github.com/topolik/liferay-portal/pull/692

Impersonation check is done by comparing the request user id with the session user id as the session still maintains the impersonator's user id. We need to check whether session user id is null as well for when there is no impersonator, ex. when a user is simply just logging in.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey Brian,

If it's customer related, please always add the [TS] designation to the subject of the PR.

@brianikim

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @lipusz ,

Thank you for catching that. I have adjusted the title.

Sincerely,
Brian Kim

**Comment by martamedio** [comment]
Hey @brianikim 

I've reviewed this PR at the request of @topolik, I have extracted the verification to a method.
It's already sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/67341

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
