### PR TITLE
LPS-68836 Regenerate system.packages.extra.mf

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
cc: @jorgeFerrer

**Comment by ealonso** [comment]
ci:retest

**Comment by topolik** [comment]
Hi @ealonso,

I'm sorry, I didn't have time to have a deep look and won't probably review it before 2017.

I know I created the ticket related to wrong preferences, but it would be better to transfer the ownership of the preferences component to you guys. I only helped Ray with that.

Thanks Edualdo.

**Comment by ealonso** [comment]
cc: @jorgeFerrer

**Comment by ealonso** [comment]
After talking with @jorgeFerrer, we've decided to send it directly to Brian. https://github.com/brianchandotcom/liferay-portal/pull/45697

**Comment by topolik** [comment]
Thanks for the update @ealonso.

**Pull request closed without merging**
