### PR TITLE
LPS-54084

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by topolik** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi @Preston-Crary,

/cc @rotty3000: can you please verify I'm correct?

I don't think we can refactor all the *Permission classes this way, we would need deeper changes.

The problem is that you use groupId as an entity primary key (classPK).

Please note this block: https://github.com/Preston-Crary/liferay-portal/blob/13c233dd90e4309b9dc3f9bae0f9efc033f81357/portal-service/src/com/liferay/portal/security/permission/BaseResourcePermission.java#L50-L60

In that block we create SCOPE_INDIVIDUAL resource permissions based on the classPK, we do it because of this new security check: https://github.com/Preston-Crary/liferay-portal/blob/13c233dd90e4309b9dc3f9bae0f9efc033f81357/portal-impl/src/com/liferay/portal/service/impl/ResourcePermissionLocalServiceImpl.java#L641-648

But we don't have primary key in those *Permission classes (e.g. [PollsPermission](https://github.com/liferay/liferay-portal/blob/master/modules/apps/polls/polls-api/src/com/liferay/polls/service/permission/PollsPermission.java)) => we should not create invalid individual permissions, they are wrong, there is no entity with primaryKey == groupId (except `Group` entity itself).

@rotty3000, how is it possible that [this permission check](https://github.com/liferay/liferay-portal/blob/master/modules/apps/polls/polls-api/src/com/liferay/polls/service/permission/PollsPermission.java#L50-51) works, when we don't have correct primary key => number of SCOPE_INDIVIDUAL resource permissions must be zero, right? 

Thank you.

**Comment by Preston-Crary** [comment]
All the permission checkers that I changed (in the portal) follow the pattern of having the groupId = classPK.

**Comment by topolik** [comment]
Yes, this is the problem. groupId is not classPK.

-- tom +

**Comment by Preston-Crary** [comment]
@topolik
@rotty3000
I took a look at https://github.com/Preston-Crary/liferay-portal/blob/master/modules/apps/polls/polls-service/src/com/liferay/polls/service/impl/PollsQuestionServiceImpl.java#L45 and https://github.com/Preston-Crary/liferay-portal/blob/master/modules/apps/wiki/wiki-service/src/com/liferay/wiki/service/impl/WikiNodeServiceImpl.java#L47.  It looks like we use these permission checkers only when we do not have access to the classPK because we are adding a new PollsQuestion or WikiNode.

However there are other cases like https://github.com/Preston-Crary/liferay-portal/blob/13c233dd90e4309b9dc3f9bae0f9efc033f81357/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppServiceImpl.java#L2656 where it makes sense to not check individual permissions.

I agree this https://github.com/Preston-Crary/liferay-portal/blob/13c233dd90e4309b9dc3f9bae0f9efc033f81357/portal-impl/src/com/liferay/portlet/documentlibrary/action/ActionUtil.java#L228 must be wrong.

Should we skip the check here https://github.com/Preston-Crary/liferay-portal/blob/13c233dd90e4309b9dc3f9bae0f9efc033f81357/portal-impl/src/com/liferay/portal/service/impl/ResourcePermissionLocalServiceImpl.java#L641-648 if the action is to add?

Would it make more sense to pass -1 as the classPK for these?

I think we should try to make it clear that these permission checkers are not for cases where a classPK is available.  Do you have any suggestions?

**Comment by topolik** [comment]
Hi @Preston-Crary 

I believe we should use portletId as the classPK not -1.

I looked at it today and found deeper problems with permission system initialization. One prevented me to reproduce even correct permissions initialization, namely, I have a problem with plugins portlets control panel permissions initialization. 

So I wasn't able to test our assumptions here :( I'm not sure it's the right time for this refactoring.

Is it possible for you to wait with it until we fix the permission system first?

**Comment by Preston-Crary** [comment]
Sure, this can wait.  Let me know when/how you want me to look into permission initialization.

**Comment by Preston-Crary** [comment]
Hey @topolik,

it's been a few months since we talked about this.  Do we still want to do something like this or should I close the LPS?

Thanks!

**Comment by topolik** [comment]
Hi @Preston-Crary,

I think we still need to revisit the code and do the cleanup. However the permission bugs are still not fixed so I'd like to ask you to wait, if possible.

Thanks!

**Pull request closed without merging**
