### PR TITLE
LPS-115048

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-115048

Based on a comment from Preston back in 2015, but the ticket was closed as inactive before we added the new logic:

https://issues.liferay.com/browse/LPS-51399?focusedCommentId=632291&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-632291

### CODE REVIEW

**Comment by topolik** [comment]
ci:forward

**Comment by holatuwol** [comment]
Ah, forgot to check source formatter since it was a one line change.

**Comment by holatuwol** [comment]
ci:test:forward

**Comment by holatuwol** [comment]
ci:forward

**Pull request closed without merging**
