### PR TITLE
LPS-87707 [TS]

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,
 we've another working version implemented with synchronization via a MultiVM cache, but since nonce authentication is not always used, it uses put replication via copy, and bootstrap for an individual cache doesn't currently work we thought this one was simpler, and lighter if functionality isn't heavily used.
Kind regards.

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,
 did you have chance to take a look to this PR?
Kind regards.

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,
 thanks a lot for your reply. I don't fully understand your point about the removal. Currently we're delegating in the type of data (DelayQueue) to handle the removal (or expiration), so that if the delay is elapsed the _cleanUp_ method will remove the nonce from the queue. 

With our change the removal code is exactly the same, we relay in the DelayQueue (one in every node) but we pass the nonce to every node. Every node mantains a DelayQueue with the same nonces, and because of that when the _NONCE_EXPIRATION time (after the creationTime) passes the nonce is removed from the queue (not in a synchronized way, but as required in the _verify_ method (as currently).

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
Hi @topolik,
 did you have time to take a look to my last comment? If you prefer I can send the pull to the core team.
Kind regards.

**Comment by topolik** [comment]
Hi @marianoalvarosaiz,

yeah, looks like we have a bug in the code. We never remove the nonces after use and let them expire. I guess we solve this by a different bug ticket.

So please feel free to send it to Core Infra for the final code polishing. From my side it's fine.

Thanks!

**Comment by marianoalvarosaiz** [comment]
see https://github.com/topolik/liferay-portal/pull/674

**Pull request closed without merging**
