### PR TITLE
[TS] LPS-89201

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-89201

Hi @topolik,

I'm sending you this PR because (I believe) the login portlet belongs to the security team.   I believe @amadeafejes sent me the pull because she believes it falls under USM territory (which it might, so I reviewed it and added some changes).

If you believe I am wrong and this should in fact go through the USM channels, please let me know so I can forward it properly.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@ChrisKian 

Please add the [TS] designation to the subject. Thanks!

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/csierra/liferay-portal/pull/483
View total diff: https://github.com/topolik/liferay-portal/compare/b9f5814758...5b48c93bc8

**Pull request closed without merging**
