### PR TITLE
[TS] LPS-71001

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-71001

Resending #483 as per the discussion among us and Dave.

Please also see [this.](https://issues.liferay.com/browse/LPS-71001?focusedCommentId=1250238&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1250238).

Regards,
Tibor

/cc @amadeafejes

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hi Tomas, @topolik 

When do you think you can go back to this?

Please let us know if you have an concerns.

Thanks,
Tibor

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
Retest after resolving merge conflicts due to rebase.

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hi Tomas,

Do you have any news on this? :-)

@topolik

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
Fixed merge conflicts.

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
This failure is actually a compile failure, not a CI error.

```
build-common-java.compile:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] Compiling 2801 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/action/UpdatePasswordAction.java:36: error: ';' expected
    [javac] import com.liferay.portal.kernel.util.GetterUtil
    [javac]                                                 ^
    [javac] 1 error
```

**Comment by lipusz** [comment]
@pyoo47 Thanks. I'm pretty sure I've already fixed it, will double check.

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:sf

**Comment by topolik** [comment]
Hi @lipusz @amadeafejes 

I found several weaknesses in this design. 

* When user submits email address we don't respond with any message. This is poor UX. We should respond with a generic message and log errors.
* `UpdatePasswordAction` is portal core class but tightly binds Login portlet  https://github.com/topolik/liferay-portal/pull/513/files#diff-c4ae85a0b66068c1415d586774663e1bR121 We need more general approach to checking the ticket validity now when only the key is insufficient and we require correct password reminder query answers. 
* The UpdatePasswordAction should be the last step in the workflow but now is executed directly from the email. It serves two purposes - change password in active session and reset password. Things will go more complex with 2FA.
* When we ask for security questions we show the token inside URL, this is currently fixed in `UpdatePasswordAction` and we need to do the same for the `ForgotPasswordMVC*Command`. So either send the redirect as POST or save the token into session
* It's possible to bypass the reminder query checks by using no `cmd` and directly send passwords: https://github.com/topolik/liferay-portal/blob/709f92cad8851e47f3d73cc0452ca1840af8ddbd/portal-impl/src/com/liferay/portal/action/UpdatePasswordAction.java#L93
* Based on https://www.troyhunt.com/everything-you-ever-wanted-to-know/ and https://postmarkapp.com/guides/password-reset-email-best-practices we should send two emails, i.e. one more when user doesn't exist
* OWASP https://www.owasp.org/index.php/Forgot_Password_Cheat_Sheet suggests to include the questions with email field in one form and then simply say "invalid information entered" when either email doesn't exist or the answers are incorrect. This might be easier way to go.

**Pull request closed without merging**
