### PR TITLE
[TECHNICAL-SUPPORT] LPS-88600 Guest Role loses View permission of Polls Display portlet after clicking Reset Changes

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @topolik, 

This pr is for issue [LPS-88600](https://issues.liferay.com/browse/LPS-88600) regarding resource permissions. See JIRA ticket and https://github.com/ricardocousolr/liferay-portal/pull/41 for background. 

Could you have a look at it? Please let me know if there's another person I should send it to.

Thanks! 

/cc @vendeltoreki

### CODE REVIEW

**Comment by topolik** [comment]
Thanks guys, I'm trying to understand the code.

Looks like the code is at two  places
 * https://github.com/liferay/liferay-portal/blob/74b357ebfefe19deee0a984600eea938182d621d/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/PermissionImporterImpl.java#L284-L291
 * https://github.com/liferay/liferay-portal/blob/fb4dea4e5a1c2d275466fd11c19508c6943d3c8a/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/PortletDataContextImpl.java#L1445-L1452

And I have a strong feeling that your changes should go into `ExportImportPermissionUtil#mergeImportedPermissionsWithExistingPermissions()` or the whole code should be refactored.

I'm still trying to find out how this works together with https://issues.liferay.com/browse/LPS-83659 and https://issues.liferay.com/browse/LPS-76213

**Comment by vendeltoreki** [comment]
Hi @topolik ,

I think you are right about placing this code in a class where it can be commonly used. It would be possible to generate a `Map<Long, String[]> roleIdsToActionIds` in `mergeImportedPermissionsWithExistingPermissions()` that only contains the records to be updated, and not the ones to be deleted (it now contains these as empty `String[]` for the given role).

However, as I see, the main problem is that currently we can't delete ResourcePermissions during import. The only service call for updating permissions is in [ExportImportPermissionUtil.updateResourcePermissions()](https://github.com/liferay/liferay-portal/blob/b3173da81b62430f7150b695d5e944b224279580/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/util/ExportImportPermissionUtil.java#L142) , and it can only add or update existing ResourcePermissions.

So technically, it would be possible to modify only these two methods: `ExportImportPermissionUtil#mergeImportedPermissionsWithExistingPermissions()` and `ExportImportPermissionUtil#updateResourcePermissions()`, where the latter can also delete the ResourcePermissions, which don't have their roleId in the `roleIdsToActionIds` map.

My thinking is, that the import should replicate whatever it finds in the LAR file under `<permissions>`, into the target's ResourcePermission records. Meaning: delete every role that is not there + update the ones that are different. But it's possible that this theory is not 100% correct.

**Comment by vendeltoreki** [comment]
FYI, this is what I was thinking of: https://github.com/vendeltoreki/liferay-portal/commit/44edcc86ec42cc1333651a3d59d386141e304ac7 . This might be a better approach.

**Comment by topolik** [comment]
Hi guys, I'm sorry, didn't get to it this week. 

If it's urgent please make sure this works together with https://issues.liferay.com/browse/LPS-83659 and https://issues.liferay.com/browse/LPS-76213 and send to appsec team for review.

Thank you.

**Comment by vendeltoreki** [comment]
Thanks, @topolik , I will check both use-cases.

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
https://github.com/csierra/liferay-portal/pull/762

**Pull request closed without merging**
