### PR TITLE
LPS-74663 Range requests create high load of I/O operations in app servers temp folder

### PR DESCRIPTION
**Pull request by JavierMoral**
https://issues.liferay.com/browse/LPS-74663
Hi @topolik ,
The main issue is explained in the LPS description but just to give some context:
To serve every request with a range header a temporary file is being created. In ServletResponseUtil.copyRange method a RandomAccessInputStream is being instanced which uses this file as an internal cache.

As random access is not needed to satisfy some requests, we've tried to avoid using it in the use cases that could be satisfied with sequential reading (see PTR-169). The use cases we've considered are the following:

- If single range is requested: we will serve it without creating a temp file.
- If non overlapping and ordered ranges are requested: we will serve them without creating a temp file.
- If overlapping and/or unordered ranges are requested: we will keep the current logic to support them (temp file will be created).

Thanks!

### CODE REVIEW

**Comment by topolik** [comment]
Hi guys,

Looks like the MP4 player sends just one request with only one range. The problem is that the code creates `RandomAccessInputStream` with the temp file also for this one-time use.

Do we need such complex solution when all we need is to fix the case when we send just one range request?

Thanks.

**Comment by topolik** [comment]
Also one more thing. Did you notice the files are not deleted after the request? We close the stream inside `finally` block so it should delete the files. But after my testing they are still there. It's probably not related but did you notice it too or it's just me?

**Comment by JavierMoral** [comment]
Hi @topolik 
Single range requests and multi range requests with sequential, non overlapping ranges are not that far away IMHO as both of them do not need random access to the stream. In this case, both of those cases were changed in an attempt to reach a solution as complete as possible product-wise. ¿Wouldn't fixing only single range requests be considered a partial solution if some other customer complains about temp files created in multi-range requests in the future?

I will try to test if the files are deleted or not asap and get back to you.

Thanks!

**Comment by JavierMoral** [comment]
Hi @topolik 
I've been performing some tests crafting multi range requests with curl and, as far as I can see, temp files are deleted once the request is answered. ¿Could you give more details about your tests?
Thanks!

**Comment by JavierMoral** [comment]
Hi @topolik 
Any news about this? Do you think the first two commits are overly complex? Is there any other way we can move this forward?
Thanks!

**Comment by topolik** [comment]
Hi guys, I think it's fine now, after you invested that much energy into it. It looks correct.

The difference is that a requests with multiple ranges are far from usual.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/52070
View total diff: https://github.com/topolik/liferay-portal/compare/8b49612d91...3ec142109e

**Pull request closed without merging**
