### PR TITLE
LPS-57826(Technical Support)

### PR DESCRIPTION
**Pull request by yuhai**
Hi Tomas, cc @daledotshan, @hhuijser

Thanks for your guide regarding the thread from https://in.liferay.com/web/global.engineering/forums/-/message_boards/view_message/16235822.

The pull request is based on https://github.com/rotty3000/liferay-portal/pull/984. So I send addition fix for you to review. Thank you in advance for your help.. :)

I added addition fix to solve our one ee customer focused issues.

The case:
1. In liferay site, create one team "team", and then assign one user "hai" to the team and d liferay site. In addition, the user "hai" own access web content's permission.
2. Create one web content folder "WCfolder" in liferay site, and then define some permission for "WCfolder", check all actions for "team" role and save.
3. Enable Liferay local staging, user "hai" login. Go to staging->web content, 

**Actual behavior: he won't own team role's permission in staging.** Because staging WCfolder's permission (regarding team role's permission) doesn't be imported into staging group .

Based on your fix regarding team, from my understanding, team only can be created for live group. That is to say, team is not stage-portlet. Team role should belong to site role and it should be used in staging group. 

If remove my fix, team role won't be used in staging group. For above example, it will cause user permission is not consistent between live and staging site.
 
Please kindly let me know if my understanding is not right.

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
Hi Tomas,

Due to the issue is from EE customer ticket. Could you please help review the pull request when you have free time?

Regards,
Hai

**Comment by topolik** [comment]
Hi Hai,

I try to review it later today, if that's OK

Ray is not responding to the pull request, I try to to find someone else who could review it.

Thank you for the patience.

**Comment by yuhai** [comment]
Thanks, :)

**Comment by topolik** [comment]
Hi,

FYI: I did the code review last week and decided to use an advice around TeamLocalService that would replace the staging groupId for live groupId.

There seem to be many places like these where we don't care about staging.

The advice should also guarantee it won't break in the future with new code.

Together with this we also need a verify process to migrate all existing teams that have wrong groupId.

**Comment by yuhai** [comment]
Hi Tomas,

Thanks for the info.

Due to the issue came from EE customer, could I firstly use the current fix to do the workaround fix for the customer? For other issues which we don't care about Team staging, we can let the customer create new tickets to report them if the customer will encounter. Is this ok?

Regards,
Hai

**Comment by topolik** [comment]
Hi,

I realized this fix is not complete and won't work properly, we need to migrate existing teams, permissions and site assignments. This current fix will create regressions - existing assignments won't be used => it would probably break permission checking that works now.

If you create a different workaround or just send parts of this one to review, please let me know so that I can count with it.

Thank you.

**Comment by yuhai** [comment]
Hi Tomas,

I create LPS-58293 to fix team role's permission regarding export/import. This is not related with staging.

https://github.com/daledotshan/liferay-portal/pull/288

Regards,
Hai

**Comment by topolik** [comment]
Hi Hai,

thank you for the update!

**Comment by topolik** [comment]
Please see https://github.com/rotty3000/liferay-portal/pull/1011

**Pull request closed without merging**
