### PR TITLE
LPS-64461 Prevent unlimited site membership requests

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Tomas. Here is my working solution as proposed.

### CODE REVIEW

**Comment by topolik** [comment]
Hi Stian,

this looks fine. Should I test it and send to Brian?

Thanks.

**Comment by stian-sigvartsen** [comment]
That's great. I am wondering if maybe we should send it to the User Management team for PT review?

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Sounds right. Thanks.

(sent from smartphone)

Dne út 13. 8. 2019 16:52 uživatel Stian Sigvartsen <notifications@github.com>
napsal:

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/pei-jung/liferay-portal/pull/504

View just my changes: https://github.com/topolik/liferay-portal/compare/stian-sigvartsen:b992f853bf...a012d076fe
View total diff: https://github.com/topolik/liferay-portal/compare/5a23c271ee...a012d076fe

**Pull request closed without merging**
