### PR TITLE
[TECHNICAL-SUPPORT] LPS-86358

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ericyanLr

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/64286
View total diff: https://github.com/topolik/liferay-portal/compare/f35c5bbfd2...c6eaa4ee0d

**Comment by topolik** [comment]
Hi @ericyanLr, 

can you please provide more details why we need this change? Why do you think presenting the download dialog is a problem?

I looked at the customer LESA ticket and it seems they are fighting with a different things:
- XSS on their usual pages, probably caused by their custom code/theme
- XSS on api/jsonws/invoke page through an error page that doesn't escape the error message correctly

Thanks!

**Comment by ericyanLr** [comment]
Hi @topolik ,

### Overview
For context, the core issue here is that **Internet Explorer** has been known to have poor support for the **application/json** MIME type. 

Liferay works around this by changing requests with MIME type **application/json** to **text/javascript**: [JSONContentTypeResponse.java#L35-L39](https://github.com/liferay/liferay-portal/blob/7.1.0-b3/portal-impl/src/com/liferay/portal/servlet/filters/jsoncontenttype/JSONContentTypeResponse.java#L35-L39)

As for this issue, the download prompt being presented appears to mainly be an IE only issue as well. This fix would be in a sense, updating our already existing workaround for handling **application/json** MIME types in **Internet Explorer**.

### Question: Why do you think presenting the download dialog is a problem?
The expected output should just be a "JSON response", which would normally just show as text in most browsers.

The download prompt dialog only shows for IE if the response contains a certain groups of characters, as detailed on the ticket.

Our thoughts on why presenting the download dialog is a potential problem is that it kind of presents a perceived security issue, where a **trusted website** is unexpectedly presenting a script for the user to download.

----

Hope that helps.

Please let me know if you have any other questions.
Thanks!

**Comment by topolik** [comment]
Hi @jonathanmccann,

thanks for the nice formatted answers! :+1: 

The problem is that once we change the content type from `application/javascript` to `text/plain` then it might create regressions for a 3rd party/customer JS that expects JSON to be returned.

Beside that, there's no real security issue with downloading the file. If we consider the "perceived security vulnerability" then I must point out that the file is never presented to users. It's very unlikely they would construct the URL manually and also it's not feasible for an attacker to construct the link and send to a victim due to p_auth token.

So far this seems to be just an artificial issue. I see no justification to change the behavior and potentially break a 3rd party code.

----

Related to the `api/jsonws/invoke` 500 error page, I meant it's Weblogic that presents the page with the JSON in it. This might be an actual issue and I would focus the effort this way.

**Comment by ericyanLr** [comment]
Hi @topolik ,

To clarify, do you mean it might create regressions for a 3rd party/customer if we change the content type from `text/javascript` to `text/plain`?

Currently, we are already changing `application/json` to `text/javascript` for IE requests.

**Comment by topolik** [comment]
Hi @ericyanLr,

well, we don't change it, the filter is disabled by default. So everybody uses `application/json`.

Only customers with compatibility issues can enable the filter to use "text/javascript" and with this fix we will, let's say, upset them, because we will break the compatibility.

Please see https://issues.liferay.com/browse/LPS-33187

Thanks.

**Comment by ericyanLr** [comment]
Hi @topolik ,

Oh right! So, for LPS-33187, this is only available for 71x/master. 
But on 70x, this filter is enabled by default. 

I figured since the file still existed on 71x/master, it would be best to make the change here as well, and so I did not make this a 70x unique fix.

---
Based on your last comment, it sounds like changing the response type from `text/javascript` to `text/plain` would likely create regressions for a 3rd party/customer.

If that's the case, would you happen to have any alternative solutions or should we just close this out as intended behavior?

----
**Side Note:** Regarding the p_auth issue, `api/jsonws/invoke` can actually be called without a p_auth value, depending on the api call.

Thanks!

**Comment by topolik** [comment]
I believe I solved the issue for you. Please look at my comment in LESA. We cannot fix their problem by fixing Liferay, they have misconfigured IIS reverse proxy.

**Comment by ericyanLr** [comment]
Thanks for your help @topolik , I'll continue monitoring the ticket.
Cheers!

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/csierra/liferay-portal/pull/643
View total diff: https://github.com/topolik/liferay-portal/compare/f35c5bbfd2...c6eaa4ee0d

**Pull request closed without merging**
