### PR TITLE
LPS-84379 FAST_LOGIN portlet is missing content padding

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/62192 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
ci:close <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Thanks @csierra !

**Pull request closed without merging**
