### PR TITLE
[TS] LPS-70181 Bookmarks entry is not visible in the staging site with a user who has the necessary roles

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-70181](https://issues.liferay.com/browse/LPS-70181)

Hi Tomas,

**Issue:** When staging content that supports ResourceBlock permissions, visibility issues may occur due to checking permission for wrong group.

**Background:** For entities using ResourceBlock permissions (e.g. BookmarksEntry) the corresponding resourceBlockId is also stored in the table. For staging and live group the ResourceBlock is different, so staged and live content refer to different ResourceBlock, meaning that checking always for live group is not sufficient.

**Note:** Similar solution was implemented in the past for [LPS-32840](https://issues.liferay.com/browse/LPS-32840)
https://github.com/liferay/liferay-portal/commit/5be1d7fec

Please let me know if you have any questions.

Thank you,
Istvan

@amadeafejes

### CODE REVIEW

**Comment by istvansajtos** [comment]
I will rebase to current master and restart ci.

**Comment by istvansajtos** [comment]
ci:stop

**Comment by istvansajtos** [comment]
ci:retest

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/47243

View just my changes: https://github.com/topolik/liferay-portal/compare/istvansajtos:19ebc187b2...e6b6914d18
View total diff: https://github.com/topolik/liferay-portal/compare/f3bc6f5a8b...e6b6914d18

**Pull request closed without merging**
