### PR TITLE
[TECHNICAL SUPPORT] LPS-95871 LDAP groups are not getting imported if the user has a comma in its name

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-95871

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi @NorbertKocsis, 
please have you retested https://issues.liferay.com/browse/LPS-79425? You removed the protection that was introduced for that. Thanks!

**Comment by NorbertKocsis** [comment]
Hi!

Hmm. I didn't stumble across that ticket. But if you check my LPS the thing is that https://issues.liferay.com/browse/LPS-80155 reintroduced LPS-79425 and I fixed it again :)

And also I used OpenLDAP during my test.

Br,
Norbert

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Already merged ... https://github.com/brianchandotcom/liferay-portal/pull/74137. Thx

**Pull request closed without merging**
