### PR TITLE
LPS-58167

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-58167 Here's my solution for the issue. CC @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Mika!

Thank you for looking into this.
I checked your solution, and as I can see, you preserved the changes to PortalImpl, but removed some (redundant) code from the MainServlet.

What if one disabled the SecureFiler from properties. Who can "protect" the request then?

@mikakoivisto @topolik

**Comment by mikakoivisto** [comment]
I believe SecureFilter is one of those mandatory filters that can’t be removed or at least shouldn’t be removed.

**Comment by lipusz** [comment]
Ok.

I think, you also need this tiny update: https://github.com/lipusz/liferay-portal/commit/673cc8d02fcb158bf4717f5380f3e720a747e47c

**Comment by lipusz** [comment]
Hi @topolik 

What do you think about Mika's solution? Can we forward it? It's getting really urgent.

**Comment by topolik** [comment]
Hi @lipusz, sorry, finally got to it. Yesterday I had internet outage and was able to process several emails only :(

**Comment by topolik** [comment]
Hey @mikakoivisto, this looks very good!

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/30157. Thank you @mikakoivisto !

**Pull request closed without merging**
