### PR TITLE
LPS-69913

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48691

**Comment by JoshuaStClair** [comment]
Is there any update on this PR? We have a client waiting on the fix so it'd be nice to have a time frame that we could relay to them if possible.

**Comment by topolik** [comment]
Hi @JoshuaStClair,

https://github.com/topolik/liferay-portal/pull/435/commits/88a84ebe3306273c313a607dd846101b70318766#diff-2db391942d010cb986db9a18c39e804eL133

By removing the `throw` statement you introduced a NPE in `return user.getUserId();` ...  `user` is null.

This NPE then shortcuts whole processing and induces safe fallback in AuthVerifierPipeline where it ignores whole TunnelAuthVerifier processing.

Can you please resend it without using NPE?

Thanks.

**Comment by topolik** [comment]
View total diff: https://github.com/topolik/liferay-portal/compare/fbfd82aba5...f15da29390

**Pull request closed without merging**
