### PR TITLE
LPS-97485

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
Just resend the PR. I am not sure the changes is right or not, because I don't understand the comment (see it https://github.com/topolik/liferay-portal/pull/798#discussion_r315125439)

BTW, SF rule check , Hugo has done that in [LPS-99876](https://issues.liferay.com/browse/LPS-99876)

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
