### PR TITLE
LPS-69487 Orphan PortletPreferences

### PR DESCRIPTION
**Pull request by ealonso**
Hey @topolik,

We've created a new method to get the orphan portlet. In this method, we are getting all portlet preferences of a layout and we are checking if those preferences match with the portlets added explicitly in a page. The portlet preferences that not match with the portlet in the page are the orphan portlets.

Please let me know if you have any question.

Thanks!!!

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @jorgeFerrer

**Comment by ealonso** [comment]
ci:reopen

**Comment by topolik** [comment]
Hi @ealonso, 

what is the relation to the embedded portlets?

I don't see this method being used so what's the purpose?

Thanks!

**Comment by ealonso** [comment]
Hey @topolik,

what is the relation to the embedded portlets?

The idea is rename this section on Layouts from "Emebeded Portlets" to "Orphan Portlets", because the name "embeded" is confuse and also we are expecting to show the preferences for portlets that not are in the page.

I don't see this method being used so what's the purpose?

We've used it on embedded_portlets.jsp, but I've forgot to add the commit using it :(.

The complete code with the rename commits and the used method is here: https://github.com/topolik/liferay-portal/pull/399, maybe I should send it first. 

Please let me know if you have any other question.

Regards,
Eudaldo.

**Comment by topolik** [comment]
Thanks I'll take a look at #399 then.

**Pull request closed without merging**
