### PR TITLE
LPS-61025 If the user gives an incorrect capcha for the first time, the user isn't being redirected to the right place

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @topolik 

My name is István Dézsi, and I'm from the Hungarian TS team in Budapest.

I'm turning to you as the Application Support team lead (please correct me, if I know this wrong).

Currently, I'm working on an issue concerning the Login portlet. 
https://issues.liferay.com/browse/LPS-61025

If the invited user fails the CAPTCHA test the first time, the URL will no longer contain the member request key parameter. In fact, all parameters will be deleted with a failed CAPTCHA verification.
The key is required in order to generate the notification for the user, so if it is lost, the user won't be notified once the logs in the first time.

I tried to circumvent this issue by extracting the key parameter from the request, and adding it to the URL. See this pull request for this solution.
It works, however, it breaks modularity because it's adding logic from one portlet (the one that sends the invitation) to the Login portlet.

My question is, do you know some other methods how the key parameter could be preserved, and also keep the Login and the Invitations portlet decoupled?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hi @topolik 

I wanted to kindly inquire whether you have found time to take a look at the pull.
If you think this issue is more relevant for another reviewer, please let me know whom to sent the pull in turn.

@zsigmondrab, @moltam89, @giros if you too have ideas where send, please let me know.

Thank you very much!

Best regards,
István

**Comment by topolik** [comment]
Hi @IstvanD,

I had a brief look. Is this reproducible without social office?

Thanks.

**Comment by IstvanD** [comment]
Hi @topolik 

It is not necessary to install the complete Social Office suite, but it requires to install so-portlet (which included the invitations portlet), and notifications-portlet.

After you have installed these portlets and their dependencies (marketplace, microblogs), place an invitation portlet to a page, and with it, send an invitation to a valid email address.

You'll receive a link in the sent email, and by clicking on it, you can test the CAPTCHA validation behavior, and after login as a new user, whether you have received the notification.

Cheers,
István

**Comment by topolik** [comment]
Hi @IstvanD,

please don't change Login portlet. It doesn't know anything about the `key` parameter.

I understand the invitation portlet needs to link the user account with the membership request, right?

Then I'd create a different sign-in/create-account URL. Instead of adding key as LoginPortlet parameter, I'd change `redirect` parameter. The redirect should contain URL to the invitation portlet with the key. After user signs in / creates the account, they would be redirected to the notification portlet but with the key. The key itself is unique and upredictable so it should be OK even to disable CSRF check for this action and call action URL on the notification portlet.

Btw. found a regression on master preventing the testing of it: https://issues.liferay.com/browse/LPS-61296

**Comment by IstvanD** [comment]
Hi @topolik 

Thanks for the explanation!

I'll implement your suggestions in the fix.

Best regards,
István

**Pull request closed without merging**
