### PR TITLE
LPS-63356

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Rebased topolik/liferay-portal/pull/321

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
I think these errors are unrelated, but I am investigating

**Comment by topolik** [comment]
Yeah, shouldn't be related. In fact are related to PR I sent yesterday to
Brian. Brian fixed it himself, somehow.

-- tom +

**Comment by stian-sigvartsen** [comment]
Ok that's great, I'll leave it for now then

**Comment by topolik** [comment]
Oh, I know, it is related!

You need to rebuild the portal-bootstrap manifest file again!

-- tom +

**Comment by stian-sigvartsen** [comment]
I rebuilt it at 11:24 today (2afb366) after rebasing it. There doesn't appear to be any new commits to master since then... but maybe I rebuilt it incorrectly?

**Comment by topolik** [comment]
Yeah, it's wrong.

master: https://github.com/liferay/liferay-portal/blob/master/modules/core/portal-bootstrap/system.packages.extra.mf#L2937-L2938
> com.liferay.portal.kernel.security.permission;version="
 1.1.0";

Yours:
https://github.com/topolik/liferay-portal/blob/2afb366cf4c78e4401e31f4d538fef64afbc8401/modules/core/portal-bootstrap/system.packages.extra.mf#L3293-L3298

> com.liferay.portal.security.permission;uses:="com.liferay.portal.ke
 rnel.bean,com.liferay.portal.kernel.exception,com.liferay.portal.kern
 el.model,com.liferay.portal.kernel.security.pacl,com.liferay.portal.k
 ernel.security.permission,com.liferay.portal.kernel.service,com.lifer
 ay.portal.kernel.spring.osgi,com.liferay.portal.kernel.xml,javax.serv
 let.http,org.apache.commons.lang.time";version="1.0.0",

**Comment by stian-sigvartsen** [comment]
I've fixed this now and rebased. Will send replacement.

**Pull request closed without merging**
