### PR TITLE
LPS-77403 Use fixed util-taglib version

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by samuelkong** [comment]
I think this fix _may_ be a bit of a overkill because this will escape and incur a performance hit anytime the namespace tag is used. [SecurityPortletContainerWrapper.check](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/SecurityPortletContainerWrapper.java#L193) ensures that the namespace will normally never contain any XSS. So the only time when there might be an XSS is on the portlet is undeployed page. I'm wondering if there might be a better way of fixing this, such as not showing the controlMenu if the portlet has been undeployed.

**Comment by topolik** [comment]
This is not the first time I see this issue. I fixed very similar one in the past and also fixed only the vulnerable part.

We need a more stable solution. This one is wrong because we can't use `escapeJS`, namespace tag is used also in HTML.

**Comment by topolik** [comment]
OK, so this is a regression of LPS-72307. They removed portletId validation from SecurityPortletContainerWrapper.check and moved it to "deploy" phase. Need to discuss why they did it in the first place. Thanks.

**Comment by topolik** [comment]
Please see https://github.com/samuelkong/liferay-portal/pull/831

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/54946. Thanks.

**Pull request closed without merging**
